minor fixes to unit tests
cakephp/cakephp pull request #10052
Opened 2017-01-16 20:55 UTC by gemal

2017-01-16 21:44 UTC, markstory commented
Looks good to me. Just waiting for travis to finish before merging.

2017-01-16 22:06 UTC, gemal commented
`Fatal error: Call to undefined method SimpleXMLElement::key() in /home/travis/build/cakephp/cakephp/vendor/phpunit/phpunit/src/Framework/Constraint/Count.php on line 59`

is that something my pull caused?

2017-01-17 00:24 UTC, markstory commented
Does the stacktrace include an assertion you changed?

2017-01-17 06:43 UTC, antograssiot requested changes
The errors in the tests suite are linked to some of your changes, see my comments.

2017-01-17 06:43 UTC, antograssiot commented on tests/TestCase/Utility/XmlTest.php
> +        $this->assertCount(2, $obj);
This change causes error in the tests suite

2017-01-17 06:43 UTC, antograssiot commented on tests/TestCase/Utility/XmlTest.php
> +        $this->assertCount(2, $obj);
As well as this one but I didn't dig why...

2017-01-17 08:38 UTC, dereuromark commented on tests/TestCase/Utility/XmlTest.php
> +        $this->assertEquals(2, count($obj));
Ideally, assertSame() to assert the same type, even though that's pretty obvious here.

2017-01-17 09:06 UTC, gemal commented
Now all the tests works :)

2017-01-17 09:10 UTC, antograssiot commented
@gemal why does your diff now includes commits that are not yours and that were merged already ?

2017-01-17 09:10 UTC, dereuromark commented
Rebasing an sqashing helps.

2017-01-17 09:15 UTC, gemal commented
I have no idea. What command do I need to run?

2017-01-17 16:07 UTC, markstory commented
@gemal You can run

```bash
git fetch upstream master
git rebase -i upstream/master
```

You may need to use a different name for `upstream` depending on what your remote names are.

2017-01-18 02:37 UTC, merged

2017-01-18 02:38 UTC, markstory commented
I squash merged this into master. Thank you for the help @gemal 👍