[2.next] Add support for having/lock options
cakephp/cakephp pull request #10163
Opened 2017-02-03 11:53 UTC by chinpei215

Fixes #9812 

I didn't add support for `LOCK IN SHARE MODE`/`FOR SHARE`/`WITH (SERIALIZABLE)` and dynamic finder, to make things simple. After this PR has been merged, I'll try to update related 2.next documents.

2017-02-04 00:48 UTC, markstory commented on lib/Cake/Test/Case/Model/Datasource/Database/SqlserverTest.php
> +		);
Should having() be in a separate test method?

2017-02-04 00:55 UTC, chinpei215 commented on lib/Cake/Test/Case/Model/Datasource/Database/SqlserverTest.php
> +		);
Do you mean I should separate `testBuildStatement` into two methods - `testBuildStatementWithHaving()` and `testBuildStatementWithLockingHint()` ?

2017-02-04 17:06 UTC, markstory commented on lib/Cake/Test/Case/Model/Datasource/Database/SqlserverTest.php
> +		);
Yes.

2017-02-04 17:07 UTC, chinpei215 commented on lib/Cake/Test/Case/Model/Datasource/Database/SqlserverTest.php
> +		);
OK. I'll do that tomorrow.

2017-02-05 13:27 UTC, chinpei215 commented
Done.

2017-02-06 14:22 UTC, ravage84 requested changes
Some nitpicking from my side.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Model/Datasource/Database/Sqlite.php
> + * Sqlite Datasource doesn't support row-level locking.
Separate with a blank line. So the first becomes the short description, the second the "long" description.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Model/Datasource/Database/Sqlite.php
> + * @return string|null
May be add a return description. With an example, may be.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Model/Datasource/Database/Sqlserver.php
> + * Currently, this method only returns WITH (UPDLOCK) when the mode is true.
Same as above.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Model/Datasource/Database/Sqlserver.php
> + * @return string|null
Same as above.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Model/Datasource/DboSource.php
> +				return trim("SELECT {$fields} FROM {$table} {$alias} {$joins} {$conditions} {$group}{$having} {$order} {$limit}{$lock}");
Quite a long line. May be asemble a line above and then return for better better readability?
Alternatively you could use multiple lines.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Model/Datasource/DboSource.php
> + * @return string|null
Return description missing.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Model/Datasource/DboSource.php
> + * @return string|null
Return description missing.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Model/Datasource/DboSource.php
> + * Currently, this method only returns FOR UPDATE when the mode is true.
Same as above.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Test/Case/Model/Datasource/Database/SqlserverTest.php
> +		$expected = 'SELECT  TOP 5 user_id, COUNT(*) AS count FROM articles AS [Article]   WHERE 1 = 1  GROUP BY user_id  HAVING COUNT(*) > 10  ORDER BY COUNT(*) DESC';
Can you split that to multiple lines, so it's not so long?

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Test/Case/Model/Datasource/Database/SqlserverTest.php
> +		$expected = 'SELECT user_id, COUNT(*) AS count FROM articles AS [Article]   WHERE 1 = 1  GROUP BY user_id  HAVING COUNT(*) > 10  ORDER BY COUNT(*) DESC  OFFSET 15 ROWS FETCH FIRST 5 ROWS ONLY';
Same as abovve.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Test/Case/Model/Datasource/Database/SqlserverTest.php
> +		$expected = 'SELECT id FROM users AS [User]  WITH (UPDLOCK)   WHERE 1 = 1   ORDER BY [id] ASC  OFFSET 15 ROWS FETCH FIRST 1 ROWS ONLY';
Same as agove.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Test/Case/Model/Datasource/Database/SqlserverTest.php
> +		$expected = 'SELECT  TOP 5 user_id, COUNT(*) AS count FROM articles AS [Article]   WHERE 1 = 1  GROUP BY user_id  HAVING COUNT(*) > 10  ORDER BY COUNT(*) DESC';
Same as above.

2017-02-06 14:22 UTC, ravage84 commented on lib/Cake/Test/Case/Model/Datasource/DboSourceTest.php
> +		$expected = 'SELECT user_id, COUNT(*) AS count FROM articles AS Article   WHERE 1 = 1  GROUP BY user_id  HAVING COUNT(*) > 10  ORDER BY COUNT(*) DESC  LIMIT 5';
Too long.

2017-02-06 14:23 UTC, ravage84 commented
@chinpei215 while you are at it, could you add ``@covers`` and ``@coversDefaultClass`` annotations to these tests? This way, the coverage will not lie about what actually is covered by your tests. 😼

2017-02-07 10:54 UTC, chinpei215 commented
@ravage84 Thanks. I'll update them when I have time.

2017-03-02 11:44 UTC, chinpei215 commented
Added return description. But I didn't split the long lines to multiple lines. I think spliting lines don't make sense as it makes difficult to copy & paste to execute the statement on SQL Command-Line tool.

2017-03-03 03:16 UTC, merged

2017-03-03 03:20 UTC, markstory commented
@chinpei215 I did a quick update to the documentation. Feel free to add more details.

2017-03-03 03:34 UTC, chinpei215 commented
@markstory Thank you as always.