[RFC] Association name setter
cakephp/cakephp pull request #10161
Opened 2017-02-03 09:53 UTC by robertpustulka

Following [comments](https://github.com/cakephp/cakephp/pull/10142).

Association names are mutable, but that change isn't reflected in a collection nor the target table. Changing association name without manually reattaching it in a collection makes it unusable. `EagerLoader` [checks if these names match](https://github.com/cakephp/cakephp/blob/3.next/src/ORM/EagerLoader.php#L496) and throws an exception. Is this exception enough or should we disallow changing association name as it would probably break it?

In other words `AssociationCollection` key, `Association` name and target `Table` alias should be identical. Changing one of them would probably break things.

My way to improve this is to check if a new association name matches the target table alias **after** it has been resolved.

There's also an issue with `AssociationCollection` not reflecting association name change, but I'm not sure we can do anything about it without changing the way associations are collected.

2017-02-04 00:41 UTC, markstory requested changes
Looks ok to me, but needs some tests.

2017-02-07 14:34 UTC, robertpustulka commented
Tests added.

2017-02-07 17:58 UTC, lorenzo commented
thanks @robertpustulka

2017-02-07 17:58 UTC, merged

2017-02-08 08:58 UTC, inoas commented
Love these kind of changes. Fail early makes my heart feel all fuzzy and secure!