Return specified default value in EntityContext
cakephp/cakephp pull request #10250
Opened 2017-02-17 15:53 UTC by nrother

With the current implementation the default value is ignored when the EntityContext was created from an array.

2017-02-17 15:56 UTC, dereuromark commented
I think we need a test case here for protection against future regression.

2017-02-17 22:14 UTC, markstory commented
Your [added tests fail](https://travis-ci.org/cakephp/cakephp/jobs/202671802).

2017-02-21 18:40 UTC, nrother commented
Ok, this seems not as simple as I thought. I'll have to have to look a bit more on this.

2017-02-22 03:14 UTC, markstory commented on tests/TestCase/View/Form/EntityContextTest.php
> +        $this->assertEquals('Articles.bar', $context->val('nottitle', ['default' => 'bar']));
Where does the `Articles` prefix come from on these values?

2017-02-22 04:12 UTC, ADmad commented
EntityContext is meant for entities in what case does is get created from array?

2017-04-16 14:11 UTC, markstory requested changes
Any updates on this? Right now this cannot be merged.

2017-04-19 09:59 UTC, nrother commented
Sorry, somehow forgot about this. The path with my fix will be taken 
when
you have a entity containing an array and you access a non-existing 
entry in
this array. Example:

```php
$entity = new Entity([
     'arr' => ['a', 'b', 'c']
]);
$ctx = $context = new EntityContext($this->request, [
     'entity' => $entity
]);
$ctx->val('arr.0') --'a'
$ctx->val('arr.99') -- null
$ctx->val('arr.99', ['default' => 'default']) --will be null, but should 
be 'default'
```

I'll try to find time to update the tests for this, but I'm more than 
open for help :)

Am 2017-04-16 16:11, schrieb Mark Story:
> @MARKSTORY requested changes on this pull request.
> 
> Any updates on this? Right now this cannot be merged.
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the
> thread [2].
> 
> 	*
> 
> Links:
> ------
> [1] 
> https://github.com/cakephp/cakephp/pull/10250#pullrequestreview-32944958
> [2]
> https://github.com/notifications/unsubscribe-auth/AGdQV2yl-TI-gJPJckeUd2qTc9A5R4qFks5rwiGdgaJpZM4MEbYA

2017-04-19 10:03 UTC, dereuromark commented
Should probably go into 3.5 now to be safer.
Some people might rely on the behavior of not having the default value here.
This can be better communicated with the migration guide on a minor IMO.

2017-04-19 19:32 UTC, markstory commented
@nrother Could the test be updated to reflect that.

2017-07-13 01:37 UTC, merged