getData() returns all when null is passed
cakephp/cakephp pull request #10264
Opened 2017-02-20 18:27 UTC by thinkingmedia

Closes #10256

2017-02-20 18:28 UTC, thinkingmedia commented
Sorry, I keep writing `getData` in the comments, but it really is `getQuery`

2017-02-20 18:43 UTC, dereuromark commented on src/Http/ServerRequest.php
> +     * is not. You can future proof your code by using the following example.
Are we sure we want to get rid of the Hash::get() convenience method here in future versions?
To me it sounds like a good idea to keep `getQuery('Post.id')` as an easier way of `Hash::get($request->getQueryParams(), 'Post.id', null);`.

2017-02-20 19:56 UTC, thinkingmedia commented on src/Http/ServerRequest.php
> +     * is not. You can future proof your code by using the following example.
@dereuromark If you want to use Guzzle as your middleware then getQuery is not a PSR-7 method, and won't exist in the request object. The point of the comment is to advise developers that if they want to be PSR-7 compliant, then don't use getQuery. It's just that ServerRequestInterface is the lower common interface between Guzzle and Cake.

I'm not saying the method will go away. But if you write your code as in the example, then you're code is more PSR-7 compliant. 

I think this was the whole point of PSR-7 support in 3.4, but I'm not completely sure on how it's going to work. I don't think we're completely there yet (i.e. you can't use Guzzle as the middleware).

Maybe I'm wrong about all this. I don't know.

2017-02-20 20:05 UTC, ADmad commented on src/Http/ServerRequest.php
> +     * is not. You can future proof your code by using the following example.
> you can't use Guzzle as the middleware

Well Guzzle itself is not a middleware, it's a HTTP client lib which is PSR-7 compliant.

2017-02-20 20:08 UTC, ADmad commented on src/Http/ServerRequest.php
> +     * is not. You can future proof your code by using the following example.
The argument you are probably looking for it if one makes a middleware which uses `$request->getQuery()` then that middleware would only be usable with CakePHP.

2017-02-20 20:09 UTC, thinkingmedia commented on src/Http/ServerRequest.php
> +     * is not. You can future proof your code by using the following example.
@ADmad okay, I have no idea how all these PSR-7 interfaces improve Cake. If any of the comments I added to the code are invalid. Please let me know, and I'll change it.

2017-02-20 20:16 UTC, ADmad commented on src/Http/ServerRequest.php
> +     * is not. You can future proof your code by using the following example.
Just remove / modify the statement `You can future proof your code..` as it be mistaken to mean that this method will be removed in future.

2017-02-21 00:20 UTC, markstory requested changes
Looks good, but it needs a test for the new return value/argument pair.

2017-02-22 11:43 UTC, ravage84 commented on src/Http/ServerRequest.php
> +     * @link http://www.php-fig.org/psr/psr-7/ This method is part of the PSR-7 server request interface.
👍

2017-02-22 14:23 UTC, thinkingmedia commented
My stupid rebase failed.

2017-02-22 14:23 UTC, closed without merging

2017-02-22 15:11 UTC, thinkingmedia commented
This PR was moved here: https://github.com/cakephp/cakephp/pull/10278