Adds Table::deleteEach() method
cakephp/cakephp pull request #10284
Opened 2017-02-22 19:05 UTC by thinkingmedia

closes #9727

- adds a new deleteEach method to the Table interface
- adds beforeDeleteEach  and afterDeleteEach events

moved from: https://github.com/cakephp/cakephp/pull/9774

2017-02-22 19:43 UTC, ADmad requested changes

2017-02-22 19:43 UTC, ADmad commented on src/ORM/Table.php
> +     * @return int Count Returns the affected rows.
Method also returns boolean.

2017-02-22 19:43 UTC, ADmad commented on src/ORM/Table.php
> +                return false;
Not sure if returning `false` if not records matching the conditions are found is the right thing to do. I would return `0` instead.

2017-02-22 20:09 UTC, thinkingmedia commented on src/ORM/Table.php
> +                return false;
@ADmad good eye, but that's a closure method. The false indicates the method should break out of the do/while loop below.

2017-02-22 20:13 UTC, dereuromark approved these changes

2017-02-22 21:15 UTC, saeideng commented on src/ORM/Table.php
> +        } while ($result);
Why you need to loop?

2017-02-22 21:18 UTC, ADmad commented on src/ORM/Table.php
> +        } while ($result);
To run the batches.

2017-02-23 02:40 UTC, markstory commented on src/ORM/Table.php
> +     * - `checkRules` boolean Defaults to true. Check deletion rules before deleting the record.
You have a mix of backticks and quotes here. Could they all be made into backticks? Those generate nicer API docs.

2017-02-23 02:40 UTC, markstory commented on src/ORM/Table.php
> +     * @return int Count Returns the affected rows.
One return type will make adding scalar hints easier.

2017-02-23 02:40 UTC, markstory commented on tests/TestCase/ORM/TableTest.php
> +            $beforeCount++;
You could increment an object property, that would save passing values by reference.

2017-02-23 02:40 UTC, markstory commented on tests/TestCase/ORM/TableTest.php
> +        }
Not a huge fan of conditionals in tests, as it makes the test code more complex. Could the cases that require branching be made into a separate test method?

2017-02-23 02:40 UTC, markstory commented on tests/TestCase/ORM/TableTest.php
> +     * @expectedException \InvalidArgumentException
You might also want to assert the message so you know the right exception case is being caught.

2017-02-23 02:51 UTC, thinkingmedia commented on tests/TestCase/ORM/TableTest.php
> +        }
@markstory sorry about that. I was rushing to finish this one. I agree this isn't good. I'll clean it.

2017-02-23 02:52 UTC, thinkingmedia commented on tests/TestCase/ORM/TableTest.php
> +     * @expectedException \InvalidArgumentException
okay

2017-02-23 02:53 UTC, thinkingmedia commented on src/ORM/Table.php
> +     * @return int Count Returns the affected rows.
@ADmad @markstory it doesn't return boolean. I think you're looking at the return statement from the closure function.

2017-02-23 06:11 UTC, ADmad requested changes

2017-02-23 06:11 UTC, ADmad commented on src/ORM/Table.php
> +                return false;
Right, i missed that.

2017-02-23 06:11 UTC, ADmad commented on src/ORM/Table.php
> +                if ($this->delete($entity, ['checkRules' => $options['checkRules']]) === false && $options['stopOnFailure']) {
The conditions for this `if` are a bit difficult to read. Saving he return value of `$this->delete()` in a var and then using in it `if` would greatly improve readability.

2017-02-23 14:11 UTC, thinkingmedia commented on src/ORM/Table.php
> +                if ($this->delete($entity, ['checkRules' => $options['checkRules']]) === false && $options['stopOnFailure']) {
@ADmad yes it's hard to read. I'll fix that.

2017-02-23 14:12 UTC, thinkingmedia commented on src/ORM/Table.php
> +        } while ($result);
@saeideng I'll had a comment in the code to explain what the loop is for.

2017-02-27 01:14 UTC, thinkingmedia commented on src/Datasource/RepositoryInterface.php
> + * @method int deleteEach($conditions, $options = []);
that interface is locked. If I add a new method it breaks BC. I'm just adding a type hint for IDEs here. The best I could do for now. I would love fix this in Cake 4. We need better interface coupling for tables.

2017-02-27 01:17 UTC, thinkingmedia commented on tests/TestCase/ORM/TableTest.php
> +        }
This shows me that some of the events I added behave very differently depending on the size of the batch. That's going to bug other developers who use them. I'm going to just simplify the events, but I don't have time tonight. I'll come back to this in the morning.

2017-02-27 01:18 UTC, thinkingmedia commented
updated, but I want to make changes to events tomorrow.

2017-02-28 08:21 UTC, robertpustulka commented on src/Datasource/RepositoryInterface.php
> + * @method int deleteEach($conditions, $options = []);
This suggests that other implementations of `RepositoryInterface` have `deleteEach()` method, but they probably don't.

2017-02-28 08:21 UTC, robertpustulka commented on src/ORM/Table.php
> +        $invalid = array_intersect(array_keys($options), ['limit', 'offset', 'page']);
Does this check make any sense? `limit`, `offset` and `page` are part of finder options.

2017-08-06 12:16 UTC, markstory commented
Closing as this cannot be merged and still needs some work. Please reopen it when you get a chance to revisit this.

2017-08-06 12:16 UTC, closed without merging