Adds support for sort order in HasMany and BelongsToMany
cakephp/cakephp pull request #10283
Opened 2017-02-22 16:47 UTC by thinkingmedia

Closes #10119

2017-02-22 16:51 UTC, dereuromark commented on src/ORM/Association/BelongsToMany.php
> +     * @param mixed $sort A find() compatible order clause
Is it possible for use to not use mixed here and be more concrete maybe?

2017-02-22 16:54 UTC, chinpei215 commented on src/ORM/Association/BelongsToMany.php
> +     * @deprecated 3.4.1 Use setSort()/getSort() instead.
I have already done this change in 3.5. I think we should avoid deprecating some methods in the bugfix release.
https://github.com/cakephp/cakephp/pull/10242

2017-02-22 16:55 UTC, thinkingmedia commented on src/ORM/Association/BelongsToMany.php
> +     * @deprecated 3.4.1 Use setSort()/getSort() instead.
@chinpei215 okay I'll remove it.

2017-02-22 20:22 UTC, markstory requested changes

2017-02-22 20:22 UTC, markstory commented on src/ORM/Association/BelongsToMany.php
> +            ->order($this->sort())
Couldn't this end up overwriting the sorts defined in the finder?

2017-02-22 20:22 UTC, markstory commented on src/ORM/Association.php
> +     * - sortOverwrite: (default true) True to replace configured sort order, false to merge.
From reading this, I'm not sure when this option takes effect or what is scope is.

2017-02-22 20:22 UTC, markstory commented on src/ORM/Association.php
> +     * - sortOverwrite: (default true) True to replace configured sort order, false to merge.
There aren't any tests covering this option in the off state.

2017-02-22 20:41 UTC, thinkingmedia commented on src/ORM/Association.php
> +     * - sortOverwrite: (default true) True to replace configured sort order, false to merge.
@markstory okay, I'll add some.

2017-02-22 20:42 UTC, thinkingmedia commented on src/ORM/Association/BelongsToMany.php
> +            ->order($this->sort())
@markstory it might, good catch. I'll have to add a test for that.

2017-02-24 13:40 UTC, ravage84 commented on src/ORM/Association/BelongsToMany.php
> +     * @var array|\Cake\Database\ExpressionInterface|string
I like the added clarity. 👍

2017-02-24 13:40 UTC, ravage84 commented on src/ORM/Association/HasMany.php
> +     * Proxies the finding operation to the target table's find method
May be divide this into short & long descriptions, if possible?

2017-02-24 13:40 UTC, ravage84 commented on src/ORM/Association/Loader/SelectLoader.php
>       * Auxiliary function to construct a new Query object to return all the records
Here, too. Dividing it into a short & long description.

2017-11-01 19:46 UTC, ADmad commented
@thinkingmedia Ping

2018-02-19 20:51 UTC, dereuromark commented
@thinkingmedia Is there still interested in getting this finished? Otherwise please close.

2018-02-19 20:54 UTC, closed without merging

2018-02-19 20:54 UTC, markstory commented
Feel free to reopen this when you get time to update it and resolve the conflicts.