3.x BTM targetBindingKey proposal
cakephp/cakephp pull request #10289
Opened 2017-02-23 11:53 UTC by inoas

Ref: https://github.com/cakephp/cakephp/issues/10288

2017-02-23 12:04 UTC, cleptric commented on src/ORM/Association/BelongsToMany.php
> +            if ($this->_targetBindingKey === null) {
Same condition again?

2017-02-23 12:04 UTC, cleptric commented on src/ORM/Association/BelongsToMany.php
> +        // $targetPrimaryKey = (array)$target->getPrimaryKey();
Accidentally left over?

2017-02-23 13:06 UTC, inoas commented on src/ORM/Association/BelongsToMany.php
> +        // $targetPrimaryKey = (array)$target->getPrimaryKey();
It is just a proposal.

2017-02-23 13:06 UTC, inoas commented on src/ORM/Association/BelongsToMany.php
> +            if ($this->_targetBindingKey === null) {
Copy-paste error. Let me fix it.

2017-02-23 13:15 UTC, inoas commented
This code already runs as part of my patched core. If you think its good I will create test cases for it.

The issue https://github.com/cakephp/cakephp/issues/10288 describes why this is desireable.

In general you can set the foreignKey and bindingKey for all associations but only the targetBindingKey for belongsToMany was missing (targetForeignKey was already there). This brings BTM in line with the other associations.

2017-02-23 13:22 UTC, dereuromark commented on src/ORM/Association/BelongsToMany.php
> +     * @var string|array
|null

2017-02-23 13:24 UTC, inoas commented on src/ORM/Association/BelongsToMany.php
> +     * @var string|array
Copied from  protected $_targetForeignKey; Patching

2017-02-23 13:41 UTC, robertpustulka commented on src/ORM/Association/BelongsToMany.php
> +    public function targetBindingKey($key = null)
Should we add and immediately deprecate method?

2017-02-23 13:46 UTC, inoas commented on src/ORM/Association/BelongsToMany.php
> +    public function targetBindingKey($key = null)
I added it for consistency sake.

2017-02-24 01:47 UTC, markstory requested changes
We will need tests before this can be merged.

2017-02-24 01:47 UTC, markstory commented on src/ORM/Association/BelongsToMany.php
> +    public function targetBindingKey($key = null)
Adding methods that are deprecated doesn't make sense to me. I would not include this method.

2017-02-24 10:08 UTC, lorenzo commented
This is missing the ability to set the keying an array. Please add it to the constructor

2017-02-24 10:09 UTC, lorenzo commented
It is also missing tests... are you also sure that was the only place where the primary key was used directly? If we are going to support this new option we need to make sure that it i used everywhere

2017-02-24 11:05 UTC, inoas commented on src/ORM/Association/BelongsToMany.php
> +    public function targetBindingKey($key = null)
Will remove.
TLDR train of thought: people using the old interface maybe want consistent access when using this

2017-02-24 11:28 UTC, inoas commented
@lorenzo this was just a proposal. It seems you are rather open to merge it once all issues are resolved and test cases have been added.

So I will look at a) where $target->getPrimaryKey() is being used and replace it with $this->getTargetBindingKey() and I will create tests. Okay?

2017-02-24 17:40 UTC, lorenzo commented
@inoas sounds good :)

2017-02-26 17:12 UTC, inoas commented
A quick look: As weak information the string `$target->getPrimaryKey()` exists throughout the framework within, **however these may not be the only cases to look at**:
- `Association::_addAssociationsToTypeMap()` (maybe wrong?)
- `Query::_addAssociationsToTypeMap()` (maybe wrong?)
- `HasMany::unlink()` (maybe wrong?)
- `ExistsIn::__invoke()` (looks 100% correct!)
- `BelongsToMany (will fix that)`
- `Marhsaller::_belongsToMany()` (will try to fix that!)

As I am not too familiar with the core and I don't want to create a massive PR, I will try to fix just BelongsToMany for now. Then I can take a look at `Marhsaller::_belongsToMany()`.

In reality all A) `->primaryKey();` and B) `->getPrimaryKey();` must be confirmed.
A quick search for all A) I would say the usage is always correct.

There are 25 total places where `->getPrimaryKey()` is being used as 3.4.2. So these need to be checked if the primaryKey is meant or the assoc binding (then bindingKey needs to be used).

2017-02-28 13:13 UTC, inoas commented
Aside the uses in class BelongsToMany I will try to patch these:

#### Association
Method: `Cake\ORM\Association::_appendNotMatching($query, $options)`
Snip: `$primaryKey = $query->aliasFields((array)$target->getPrimaryKey(), $this->_name);`
Ref: https://github.com/cakephp/cakephp/blob/e91a091b269c35719cf7476d1bb1c8f3815308b6/src/ORM/Association.php#L956

#### Mashaller
Method: `Cake\ORM\Marshaller::_belongsToMany(Association $assoc, array $data, $options = [])`
Snip: `$primaryKey = array_flip((array)$target->getPrimaryKey());`
Ref: https://github.com/cakephp/cakephp/blob/28ea54b6a89c17dd9e30aa390e4d6b35a7c3daee/src/ORM/Marshaller.php#L367

Method: `Cake\ORM\Marshaller::_loadAssociatedByIds($assoc, $ids)`
Snip: `$primaryKey = (array)$target->getPrimaryKey();`
Ref: https://github.com/cakephp/cakephp/blob/28ea54b6a89c17dd9e30aa390e4d6b35a7c3daee/src/ORM/Marshaller.php#L457

#### Query
Method: `Cake\ORM\Query::_addAssociationsToTypeMap($table, $typeMap, $associations)`
Snip: `$primary = (array)$target->getPrimaryKey();`
Ref: https://github.com/cakephp/cakephp/blob/28ea54b6a89c17dd9e30aa390e4d6b35a7c3daee/src/ORM/Query.php#L414

2017-02-28 13:23 UTC, lorenzo commented
> Method: Cake\ORM\Association::_appendNotMatching($query, $options)

Not needed, the method is overridden in BelongsToMany

> Method: Cake\ORM\Marshaller::_belongsToMany(Association $assoc, array $data, $options = [])

Yes, this will need to change

> Method: Cake\ORM\Marshaller::_loadAssociatedByIds($assoc, $ids)

Probably? I'm currently not sure about the need to change these, given that the feature is called `_ids` and you associate them directly by primary key.


> Method: Cake\ORM\Query::_addAssociationsToTypeMap($table, $typeMap, $associations)

No, you can leave this alone :)

2017-09-26 09:56 UTC, robertpustulka commented
@inoas still interested in finishing this?

2017-09-26 10:47 UTC, inoas commented
The only thing missing are a few unit tests, right?
I am very constrained at the moment with time, but if you can point me at where I would find similar unit tests I could adapt them to the double-sided custom foreign key setup here and then see if I can make them work...

2017-09-26 10:51 UTC, inoas commented
This needs to be done:

>> Needs to change?:
>> Method: Cake\ORM\Marshaller::_belongsToMany(Association $assoc, array $data, $options = [])

> Yes, this will need to change

My expertise with the ORM internals is not sufficient to judge upon this:

>> Needs to change?:
> > Method: Cake\ORM\Marshaller::_loadAssociatedByIds($assoc, $ids)

> Probably? I'm currently not sure about the need to change these, given that the feature is called _ids and you associate them directly by primary key.

2019-08-07 23:44 UTC, dereuromark commented
Do we still want to merge this into 3.x or 4.x?

2019-11-22 05:23 UTC, closed without merging

2020-06-26 04:29 UTC, infokani commented
> Do we still want to merge this into 3.x or 4.x?

Really need this feature

2020-06-26 04:40 UTC, othercorey commented
This should be fixed in 4.1. 

https://github.com/cakephp/cakephp/pull/14377

2020-06-26 04:41 UTC, ADmad commented
> Really need this feature

You can cleanup this patch and submit a new pull request. Simply waiting for someone else to do it for you won't help, as evident from this closed PR :)

2020-06-26 04:42 UTC, ADmad commented
> This should be fixed in 4.1.

Ah well, guess someone else did implement it :)