Dropdown select limit (view limit) option for Paginator
cakephp/cakephp pull request #10301
Opened 2017-02-24 19:12 UTC by eather009

Dropdown array for Select limit

@param array $limits This is array of options.
@param int|null $default Default limit for option selecting. Default value is $this->param('perPage').
@param array $options Options for Select tag attributes like class, id or event
@return string html output.

This will help to show by data limit for per page without writing extra code, just add following code will give you below image output.

`$this->Paginator->limitControl()`

<img width="109" alt="limit_control" src="https://cloud.githubusercontent.com/assets/4234756/23317055/1d6b9200-faf7-11e6-9b78-78c90c8f8971.png">

Also override select tag attribute can be possible by passing $options.

Thank you

2017-02-25 06:30 UTC, ADmad commented on src/View/Helper/PaginatorHelper.php
> +            $limits += ['0' => __('All'), '20' => '20', '50' => '50', '100' => '100'];
0 limit makes no sense.

2017-02-25 10:13 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +            $limits += ['0' => __('All'), '20' => '20', '50' => '50', '100' => '100'];
Im getting error 
codecov/project — 94.9% (-0.14%) compared to 4180750 and 
codecov/patch — 91.66% of diff hit (target 95.03%) but I don't know why. Thus set 0 to check whether it has any dependency or not.

2017-02-25 12:10 UTC, ADmad commented on src/View/Helper/PaginatorHelper.php
> +            $limits += ['0' => __('All'), '20' => '20', '50' => '50', '100' => '100'];
That's probably because you haven't added any tests case calling the method without any params.

2017-02-25 13:56 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +            $limits += ['0' => __('All'), '20' => '20', '50' => '50', '100' => '100'];
Thank you. Ya, that was my missing.

2017-02-27 20:18 UTC, ravage84 requested changes

2017-02-27 20:18 UTC, ravage84 commented on src/View/Helper/PaginatorHelper.php
> +     *
No white line.

2017-02-27 20:18 UTC, ravage84 commented on src/View/Helper/PaginatorHelper.php
> +     * dropdown array for Select limit
Dropdown select for pagination limit

2017-02-27 20:18 UTC, ravage84 commented on src/View/Helper/PaginatorHelper.php
> +     * @param array $limits This is array of options.
The options array.

2017-02-27 20:18 UTC, ravage84 commented on src/View/Helper/PaginatorHelper.php
> +     * @param int|null $default Default limit for option selecting. Default value is $this->param('perPage').
`````
Default option for pagination limit. Defaults to ``$this->param('perPage')``.

2017-02-27 20:18 UTC, ravage84 commented on src/View/Helper/PaginatorHelper.php
> +            $limits = [
Since these values can vary greatly between applications,, I'm not sure if it makes much sense to set such fallbacks.

2017-02-27 20:18 UTC, ravage84 commented on src/View/Helper/PaginatorHelper.php
> +        if (!in_array($default, $limits)) {
Does it make sense to be able to set the default to a value that is not a valid option?

2017-02-27 20:18 UTC, ravage84 commented on src/View/Helper/PaginatorHelper.php
> +        ksort($limits);
Not sure everybody wants to have it sorted this way. I could imagine some want to have a poplular value on top of the list.

2017-02-27 20:18 UTC, ravage84 commented on src/View/Helper/PaginatorHelper.php
> +        $out .= $this->Form->control('limit', ($options + ['type' => 'select', 'label' => __('View'), 'value' => $default, 'options' => $limits, 'onChange' => 'this.form.submit()']));
Line too long.
What's with that bracket before $options?
May be put that into a separate assignment before assembling the output.

2017-02-27 20:18 UTC, ravage84 commented on tests/TestCase/View/Helper/PaginatorHelperTest.php
> +        $out = $this->Paginator->limitControl([], null, ['class' => 'form-control']);
Setting the default option is not tested.

2017-02-27 20:48 UTC, dereuromark commented on src/View/Helper/PaginatorHelper.php
> +            $limits = [
Some defaults are OK IMO.

2017-03-01 17:07 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +            $limits = [
Users can set any options, even they may want keep it default, which will help user to get default options. So, this condition is given.

2017-03-01 17:10 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +        if (!in_array($default, $limits)) {
Actually, this have another usage. I am using cache for pagination limit which will stored each page pagination limit value. Now, if anyone wants his own value which is not included in the Limit options, that will be added to the limits. 

Yes, in one sense, this really doesn't make sense here unless anyone using caching or other technique on pagination

2017-03-01 17:11 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +        ksort($limits);
The reason is same as before I mentioned in previous comment. Actually, this was used for my own purpose. I can remove this. Thank you

2017-03-01 17:20 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +     *
Thank you. Given.

2017-03-01 17:21 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +     * @param array $limits This is array of options.
Thank you. Given.

2017-03-01 17:21 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +     * dropdown array for Select limit
Thank you. Updated.

2017-03-01 17:21 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +        if (!in_array($default, $limits)) {
Thank you. Updated.

2017-03-01 17:21 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +        ksort($limits);
Thank you. Updated.

2017-03-01 17:21 UTC, eather009 commented on tests/TestCase/View/Helper/PaginatorHelperTest.php
> +        $out = $this->Paginator->limitControl([], null, ['class' => 'form-control']);
Thank you. Updated.

2017-03-01 17:21 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +        $out .= $this->Form->control('limit', ($options + ['type' => 'select', 'label' => __('View'), 'value' => $default, 'options' => $limits, 'onChange' => 'this.form.submit()']));
Thank you. Updated.

2017-03-06 16:04 UTC, dereuromark approved these changes

2017-03-07 01:48 UTC, markstory commented on src/View/Helper/PaginatorHelper.php
> +     * Dropdown select for pagination limit
Might be good to mention that this will also generate the wrapping form as I am sure someone will put this inside an already open search form.

2017-03-08 04:13 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +     * Dropdown select for pagination limit
Ya. Sure. Giving update

2017-03-08 04:33 UTC, eather009 commented on src/View/Helper/PaginatorHelper.php
> +     * Dropdown select for pagination limit
Thank you. Its given

2017-04-29 18:51 UTC, dereuromark commented
Should we accept and merge this? Is everything in order now?

2017-05-02 01:27 UTC, merged