Update BasicAuthenticate To Support Different Encodings Than ISO-8859-1
cakephp/cakephp pull request #10360
Opened 2017-03-06 12:58 UTC by Manuel1948

The problem is that basic authentication credentials are encoded in ISO-8859-1, but if you use an other encoding f.e. UTF-8 and the Auth component compares a username or password with special chars it comes to errors.

So I added a check if there is set another valid encoding than ISO-8859-1 and if so, convert it to the actual encoding.

2017-03-06 13:13 UTC, Manuel1948 commented
Issue #10359

2017-03-06 13:25 UTC, cleptric commented
Could please add a test case for that.

2017-03-06 13:25 UTC, dereuromark commented on src/Auth/BasicAuthenticate.php
> +        if ($encoding && in_array($encoding, mb_list_encodings()) && $encoding != 'ISO-8859-1') {
Please use !==

2017-03-06 13:26 UTC, dereuromark commented on src/Auth/BasicAuthenticate.php
> +            $pass = mb_convert_encoding($pass, $encoding, 'ISO-8859-1');
Ideally that string is a constant in that class, so we don't have to use a magic string 3 times (with the chance of typos).

2017-03-06 13:35 UTC, cleptric commented
I'm also not sure, if they are always ` ISO-8859-1` encoded. Isn't that depending of our php.ini settings?

2017-03-06 13:36 UTC, Manuel1948 commented on src/Auth/BasicAuthenticate.php
> +            $pass = mb_convert_encoding($pass, $encoding, 'ISO-8859-1');
thx

2017-03-06 13:36 UTC, Manuel1948 commented on src/Auth/BasicAuthenticate.php
> +        if ($encoding && in_array($encoding, mb_list_encodings()) && $encoding != 'ISO-8859-1') {
thx

2017-03-06 13:37 UTC, dereuromark commented
Indeed, this sounds like we should get the input encoding from a more dynamic source rather than a hardcoded string.

2017-03-06 13:41 UTC, cleptric commented
Which then leads me to the questions if this can't be fixed by just updating your php.ini?

2017-03-06 13:44 UTC, Manuel1948 commented
Dear cleptric,

can you suggest me a change in php.ini because my default charset is UTF-8 but this not the solution :/

2017-03-06 14:02 UTC, Manuel1948 commented
http://toscho.de/2009/authentifizierung-php-utf-8/ 

I edited the commits again based on this page.

2017-03-06 14:11 UTC, dereuromark commented on src/Auth/BasicAuthenticate.php
> +            $username = mb_convert_encoding($username, $encoding, self::ENCODING_SOURCES);
Late static binding (static::) helps to allow extensions to work with their own const.

2017-03-06 14:18 UTC, Manuel1948 commented on src/Auth/BasicAuthenticate.php
> +            $username = mb_convert_encoding($username, $encoding, self::ENCODING_SOURCES);
I'm a bit confused now, should I correct the :: to -> or is it okay?

2017-03-06 14:20 UTC, ADmad commented on src/Auth/BasicAuthenticate.php
> +            $username = mb_convert_encoding($username, $encoding, self::ENCODING_SOURCES);
You need to use `::static` instead of `::self`

2017-03-06 14:23 UTC, Manuel1948 commented on src/Auth/BasicAuthenticate.php
> +            $username = mb_convert_encoding($username, $encoding, self::ENCODING_SOURCES);
Thank you, I'm not that expert as you are

2017-03-06 19:45 UTC, markstory requested changes
A test case is required to merge this. It will regress to easily in the future without a test case.

2017-03-06 19:55 UTC, Manuel1948 commented
Hope someone can write a test case, because I can't :/

2018-05-17 12:49 UTC, closed without merging

2018-05-17 13:15 UTC, Manuel1948 commented
This problem isn't currently reproducable anymore, looks like something has changed this behavior.