Minor updates (annotations and best-practices)
cakephp/cakephp pull request #10534
Opened 2017-04-17 10:45 UTC by Theaxiom

This is me splitting up a larger PR, please see #10532 for details.

2017-04-17 10:47 UTC, Theaxiom commented on src/Database/Schema/SqlserverSchema.php
> +        if (
Ahh, forgot to cherry-pick the commit that fixed that. Pulled it into the PR now.

2017-04-17 11:40 UTC, Theaxiom commented
Looks like I have to fix `src/Database/Schema/Sqlserverschema.php`

2017-04-17 11:49 UTC, Theaxiom commented on src/Database/Schema/SqlserverSchema.php
> +        if ($data['type'] === 'integer' || ($data['type'] === 'biginteger') {
Fixed.

2017-04-17 12:25 UTC, lorenzo commented on src/Database/Dialect/SqliteDialectTrait.php
> +                            $value = strtolower(rtrim($p, 's'));
`rtrim('THINGS', 's')` is not the same as `rtrim('things', 's')`

2017-04-17 12:26 UTC, lorenzo commented on src/ORM/Association.php
> +        if (empty($fields) && !$autoFields && $options['includeFields'] && ($fields === null || $fields !== false)) {
This is very difficult to read. Why change it?

2017-04-17 21:38 UTC, Theaxiom commented on src/Database/Dialect/SqliteDialectTrait.php
> +                            $value = strtolower(rtrim($p, 's'));
You are indeed correct.

2017-04-18 08:51 UTC, inoas requested changes

2017-04-18 08:51 UTC, inoas commented on src/Event/Decorator/ConditionDecorator.php
> +            return !($condition === 'unless');
The code before may be slightly more verbose but a lot better to read.

2017-04-18 08:51 UTC, inoas commented on src/Filesystem/File.php
> +        return is_dir($dir) && is_writable($dir) && !$this->exists() && touch($this->path);
Worse to read

2017-04-18 08:51 UTC, inoas commented on src/Filesystem/Folder.php
> +            return false;
Existing bail early is better practice.
Also such code changes unless accompanied by a specific unit test can introduce silent bugs

2017-04-18 08:51 UTC, inoas commented on src/Http/Response.php
> +        $result->setTimezone(new DateTimeZone('UTC'));
Is the method called setTimeZone?

2017-04-18 08:51 UTC, inoas commented on src/Database/Driver/PDODriverTrait.php
> +        return $this->_connection->rollBack();
Is the method called rollBack?

2017-04-18 08:51 UTC, inoas commented on src/Validation/ValidationRule.php
> +            if (($this->_on === 'create' && !$newRecord) || ($this->_on === 'update' && $newRecord)) {
I think this is okay to make comparison operator precedence explict.

2017-04-18 08:51 UTC, inoas commented on src/Validation/ValidationRule.php
> +            if (($this->_on === 'create' && !$newRecord) || ($this->_on === 'update' && $newRecord)) {
Aka was okay before

2017-04-18 08:53 UTC, dereuromark commented on src/Validation/ValidationRule.php
> +            if (($this->_on === 'create' && !$newRecord) || ($this->_on === 'update' && $newRecord)) {
Being a bit more explicit here doesnt hurt.

2017-04-18 08:53 UTC, dereuromark commented on src/Http/Response.php
> +        $result->setTimezone(new DateTimeZone('UTC'));
setTimezone() is the method. So :+1: here

2017-04-18 08:54 UTC, dereuromark commented on src/Database/Driver/PDODriverTrait.php
> +        return $this->_connection->rollBack();
rollback() is the method name, so :-1:  here.

2017-04-18 09:10 UTC, dereuromark commented on src/Filesystem/File.php
> +
Why this newline? Shouldnt be there IMO.

2017-04-18 09:11 UTC, dereuromark commented on src/Template/Element/plugin_class_error.ctp
> -?>
Templates should keep the closing tags - as they are mainly HTML, and there might be some more HTML that wants to be added below at some point.

2017-04-19 00:12 UTC, Theaxiom commented on src/Filesystem/File.php
> +
New line before return, CS rule.

2017-04-19 00:12 UTC, Theaxiom commented on src/Template/Element/plugin_class_error.ctp
> -?>
Then I would say update all the templates to include closing PHP tags.

2017-04-19 00:13 UTC, Theaxiom commented on src/Template/Element/plugin_class_error.ctp
> -?>
nvm, I just checked, the others don't require it

2017-04-19 00:13 UTC, markstory commented on src/Template/Element/plugin_class_error.ctp
> -?>
Not sure templates need a closing `?>` if they end in a PHP block.

2017-04-19 00:15 UTC, dereuromark commented on src/Filesystem/File.php
> +
No, never as a single rested line.

2017-04-19 00:16 UTC, Theaxiom commented on src/Filesystem/File.php
> +
Ok, I will fix it. Thanks. 👍

2017-04-19 00:17 UTC, dereuromark commented on src/Template/Element/plugin_class_error.ctp
> -?>
It makes it easier to add HTML below - without the hasle of having to add the closing tag again as well.

2017-04-19 00:18 UTC, Theaxiom commented on src/Template/Element/plugin_class_error.ctp
> -?>
I think I am inclined to agree with @dereuromark

2017-04-19 00:27 UTC, Theaxiom commented
Is this PR ready? Please let me know if anything else needs to be addressed. 👍

2017-04-29 18:04 UTC, dereuromark commented
Looks like this can be merged.

2017-04-29 18:23 UTC, merged