Getters and setters for I18n/I18n.php
cakephp/cakephp pull request #10577
Opened 2017-04-24 10:49 UTC by burzum

2017-04-24 10:55 UTC, dereuromark commented on src/I18n/I18n.php
> +     * @deprecated Deprecated since 3.5. Use setLocale() and getLocale().
You dont have to repeat the deprecated part :)
The consistent way across the newer deprecations so far always was:

    @deprecated 3.4.0 Use setTypes()/getTypes() instead.

2017-04-24 11:08 UTC, dereuromark commented on src/I18n/I18n.php
> +    public static function setTranslator($name = 'default', $locale = null, callable $loader)
If loader is not a nullable (optional) argument anymore, maybe the order should be changed here for the setter?

2017-04-24 12:22 UTC, burzum commented on src/I18n/I18n.php
> +    public static function setTranslator($name = 'default', $locale = null, callable $loader)
The problem is it seems that the default name of value `default` is expected. I was looking into changing it to `($name, callable $loader, $locale = null)`.

If we're OK with that I'll do it. BC can be maintained by translator() by passing `default` as it is.

2017-04-24 18:55 UTC, dereuromark commented on src/I18n/I18n.php
> +     *  I18n::translator('default', 'fr_FR', function () {
they seem outdated now.

2017-04-24 19:25 UTC, markstory requested changes
It would be good to get tests for the newly added methods.

2017-04-24 19:25 UTC, markstory commented on src/I18n/I18n.php
> +     *  new MessagesFileLoader('my_translations', 'custom', 'po');
This example doesn't match the parameter order in the function signature.

2017-04-25 14:39 UTC, ravage84 commented on src/I18n/I18n.php
> +     * translator instances. By default the `default` and `sprintf` formatters
Can be slit up in short and long description.

2017-04-25 14:39 UTC, ravage84 commented on src/I18n/I18n.php
> +     * the value as stored in the `intl.default_locale` PHP setting before
Can be slit up in short and long description.

2017-04-25 14:39 UTC, ravage84 commented on src/I18n/I18n.php
> +     * This also affects the `intl.default_locale` PHP setting.
Can be slit up in short and long description.

2017-04-25 14:39 UTC, ravage84 commented on src/I18n/I18n.php
> +     * locale. If no locale is passed then it takes the value returned by the `getLocale()` method.
Can be slit up in short and long description.

2017-05-15 01:51 UTC, markstory commented on src/I18n/I18n.php
> +     * as the last argument of this function.
Callable isn't the last argument though.

2017-06-03 01:55 UTC, merged