Adding a getter and setter for cache registry
cakephp/cakephp pull request #10576
Opened 2017-04-24 00:43 UTC by burzum

2017-04-24 02:05 UTC, Theaxiom approved these changes

2017-04-24 08:20 UTC, cleptric commented on src/Cache/Cache.php
> +     * @param \Cake\Core\ObjectRegistry|null $registry Injectable registry object.
`null` is obsolete now

2017-04-24 08:20 UTC, cleptric commented on src/Cache/Cache.php
> +     * @deprecated Use getRegistry() and setRegistry() instead.
Could we add the version number?

2017-04-24 10:10 UTC, burzum commented on src/Cache/Cache.php
> +     * @deprecated Use getRegistry() and setRegistry() instead.
OK, but why do you need it? I don't think *any* other deprecated method has the version number included.

2017-04-24 10:32 UTC, cleptric commented on src/Cache/Cache.php
> +     * @deprecated Use getRegistry() and setRegistry() instead.
That's not true. A quick search for `@deprecated` inside the core reveals that basically all methods have a version number attached to the annotation.
Main reason here is to be consistent :)

2017-04-24 10:33 UTC, Theaxiom commented on src/Cache/Cache.php
> +     * @deprecated Use getRegistry() and setRegistry() instead.
If that's the case, we should also raise an issue against any deprecation notices which omit the deprecated version number.

2017-04-24 10:34 UTC, burzum commented on src/Cache/Cache.php
> +     * @deprecated Use getRegistry() and setRegistry() instead.
Yes, I'm not 100% sure but I haven't seen any version in these lines before. Were they added recently?

2017-04-24 10:45 UTC, cleptric commented on src/Cache/Cache.php
> +     * @deprecated Use getRegistry() and setRegistry() instead.
We normally just add them when we deprecate stuff.

@Theaxiom There are just a few methods that missing the version. I guess it's a little bit time consuming to scrape through the history to find the right version. A PR addressing this is of course welcomed at any time 😀

2017-04-25 01:22 UTC, markstory commented on src/Cache/Cache.php
> +     * Returns the Cache Registry instance used for creating and using cache adapters.
But it doesn't return anything..

2017-04-25 01:23 UTC, markstory requested changes
Would be good to have some tests for the new methods.

2017-04-26 10:47 UTC, ravage84 requested changes

2017-04-26 10:47 UTC, ravage84 commented on src/Cache/Cache.php
> +     * Returns the Cache Registry instance used for creating and using cache adapters.
Probably Copy Pasta error.

2017-04-26 10:47 UTC, ravage84 commented on src/Cache/Cache.php
> +     * @deprecated Deprecated since 3.5. Use getRegistry() and setRegistry() instead.
Move below return.

2017-05-10 13:20 UTC, burzum commented
@markstory I've added tests, please review again.

2017-05-10 21:02 UTC, saeideng commented on src/Cache/Cache.php
> +    public static function getEngine($config)
we have not setter method for `Engine() ` , so we no need to `getEngine()`

2017-05-11 00:55 UTC, markstory commented on src/Cache/Cache.php
> +    public static function getEngine($config)
Agreed.

2017-05-16 01:21 UTC, merged