Adding getters and setters for logger objects
cakephp/cakephp pull request #10638
Opened 2017-05-10 11:35 UTC by burzum

Added getters and setters for two classes.

2017-05-10 11:44 UTC, dereuromark commented on src/Database/Connection.php
> -            if ($this->_logger === null) {
This is Inside the new method. Looks BC.

2017-05-10 11:46 UTC, burzum commented on src/Database/Connection.php
> -            if ($this->_logger === null) {
Can I write the doc block like this?

```php
    /**
     * {@inheritDoc}
     * @@deprecated 3.5.0 Use getLogger() and setLogger() instead.
     */
```

2017-05-10 11:48 UTC, cleptric commented on src/Database/Connection.php
> -            if ($this->_logger === null) {
Ahh, overlooked that 😇
@burzum minus one @ and an added blank line after `{@inheritDoc}`, yes 😄

2017-05-10 11:51 UTC, burzum commented on src/Database/Log/LoggingStatement.php
> +    /**
It's there? I'm blind? What exactly is it complaining about?

2017-05-10 18:10 UTC, robertpustulka requested changes

2017-05-10 18:10 UTC, robertpustulka commented on src/Database/Connection.php
> +     * @return void
Can you return `$this` for method chaining?

2017-05-10 21:06 UTC, markstory commented on src/Database/Log/LoggingStatement.php
> +        $this->_logger = $logger;
Should return $this here.

2017-05-12 13:21 UTC, ravage84 commented on src/Database/Connection.php
> -            if ($this->_logger === null) {
@burzum personally, I prefer to have blank line after inheriting, as it makes it more visible that I inherit and what I overwrite/add.

2017-05-12 13:23 UTC, ravage84 commented on src/Database/Log/LoggingStatement.php
> +     * @deprecated 3.5.0 Use getLogger() and setLogger() instead.
Can we set ``@deprecated`` to the end of the annotations?

2017-05-14 23:00 UTC, burzum commented on src/Database/Log/LoggingStatement.php
> +     * @deprecated 3.5.0 Use getLogger() and setLogger() instead.
It's on top in other places!?

2017-05-14 23:05 UTC, burzum commented on src/Database/Log/LoggingStatement.php
> +        $this->_logger = $logger;
Done.

2017-05-15 01:58 UTC, markstory commented on src/Database/Log/LoggingStatement.php
> +     * @deprecated 3.5.0 Use getLogger() and setLogger() instead.
Or it could not matter :smile:

2017-05-15 02:01 UTC, markstory commented on src/Database/Log/LoggingStatement.php
> +        $this->_logger = $logger;
I don't see it changed here. I see it changed in `Connection`.

2017-05-15 06:55 UTC, robertpustulka commented on src/Database/Log/LoggingStatement.php
> +     * @return object logger instance
Shouln't that be `@return Cake\Database\Log\QueryLogger` ?

2017-05-15 07:28 UTC, dereuromark commented on src/Database/Log/LoggingStatement.php
> +     * @deprecated 3.5.0 Use getLogger() and setLogger() instead.
As Long as we dont have a sniffer for it to automate.

2017-05-15 10:16 UTC, burzum commented on src/Database/Log/LoggingStatement.php
> +     * @deprecated 3.5.0 Use getLogger() and setLogger() instead.
I really don't care, my point is that it is a common PITA that one person tells you to do it this way, then somebody else comes in tells you the opposite. So I would like to get phpcs to detect it and enforce you to do it right or at least a wiki page for reference to look it up.

2017-05-15 10:18 UTC, dereuromark commented on src/Database/Log/LoggingStatement.php
> +     * @deprecated 3.5.0 Use getLogger() and setLogger() instead.
I agree, before there are no clear sniffers/guidelines it is not worth it.
And I agree, the order it currently is is fine.
```
@other
@param
@throws
@return
```
usually

2017-05-15 12:12 UTC, ravage84 commented on src/Database/Log/LoggingStatement.php
> +     * @deprecated 3.5.0 Use getLogger() and setLogger() instead.
I agree, we should have a) section about the order of the doc block annotations in our [coding standards page in the CookBook](https://book.cakephp.org/3.0/en/contributing/cakephp-coding-conventions.html#commenting-code) and b) a sniff that can bug people, so I don't need to :trollface: 

@dereuromark I just searched for ``@deprecated`` in the 3.x code and my findings (samples) disagree with your order.

It seems the following is used most often (which I also remember we used normally):

````
@param
@return
@throws
@other
````

[Search on GitHub repo for "deprecated"](https://github.com/cakephp/cakephp/search?p=3&q=deprecated&type=&utf8=%E2%9C%93).

But we _could_ use the yet to be written sniff to tell us which order results in more violations in the current code and we then use the one that results in the least violations.
Though, I still prefer the ordering above, as it makes more sense to me (order of importance & of usage).

2017-05-16 01:20 UTC, markstory commented on src/Database/Log/LoggingStatement.php
> +     * @return object logger instance
I'll fix these type errors up post merge.

2017-05-16 01:20 UTC, merged