Enhancements to ObjectRegistry.
cakephp/cakephp pull request #10631
Opened 2017-05-08 19:24 UTC by robertpustulka

I've added `return $this` for method chaining and implemented `__set()`, `__isset()`, `IteratorAggregate` and `Countable`.

2017-05-09 01:02 UTC, markstory commented
Reasonable thing to add, but you have failing tests, and need tests for the new methods.

2017-05-09 01:03 UTC, markstory requested changes
Reasonable thing to add, but you have failing tests, and need tests for the new methods.

2017-05-09 08:27 UTC, lorenzo commented
Looks good to me :)

2017-05-09 12:22 UTC, robertpustulka commented
@markstory is that OK to test new methods only in `ComponentRegistry`? `ObjectRegistry` is abstract and has never had it's tests.

2017-05-09 14:16 UTC, ADmad commented
@robertpustulka I think having tests for `ComponentRegistry` is fine. If you were to add tests for the abstract class you would require phpunit mock which i believe internally would just make a class which extends the abstract class :)

2017-05-09 14:19 UTC, robertpustulka commented
@ADmad I usually test abstract classes using mocks. This one doesn't have test, and I don't think it's necessary right now. Maybe in 4.0 :)

2017-05-10 00:16 UTC, markstory commented on tests/TestCase/Controller/ComponentRegistryTest.php
> +    public function testUset()
Typo in the method name.

2017-05-10 00:16 UTC, markstory approved these changes

2017-05-10 13:36 UTC, robertpustulka commented on tests/TestCase/Controller/ComponentRegistryTest.php
> +    public function testUset()
@markstory I think you're referencing the old commit. It's been fixed.

2017-05-10 14:08 UTC, ADmad commented
@robertpustulka Does this mean we can use `ObjectRegistry` in authentication plugin instead of custom collection class ? :)

2017-05-10 14:15 UTC, robertpustulka commented
@ADmad we already do :)

2017-05-11 01:28 UTC, merged