3.next - Add application routes hook
cakephp/cakephp pull request #10646
Opened 2017-05-12 02:30 UTC by markstory

This finishes off the bulk of the work for #10308. I'm expanding the scope of the `Application` class to be a vessel for configuration/setup logic. This change also enables us to deprecate most of the static methods on `Router` (in a subsequent pull request) which will let us significantly reduce the static API surface area in CakePHP.

## TODO

* [ ] Test these changes against an 3.2 style app to ensure backwards compatibility for route reloading.
* [ ] Should `RouteBuilder` have an interface added?

2017-05-12 07:47 UTC, lorenzo commented on src/Routing/Router.php
> +    public static function getRouteBuilder($path, array $options = [])
Can we rename this to `createRouteBuilder` or `newRouteBuilder`, so that it does not give the impression it is the same one every time?

2017-05-12 07:52 UTC, lorenzo commented on tests/TestCase/Routing/RouterTest.php
> -        $request->env('HTTP_HOST', 'localhost');
Nice!

2017-05-12 07:54 UTC, lorenzo commented
This looks great!

2017-05-12 08:17 UTC, ADmad requested changes

2017-05-12 08:17 UTC, ADmad commented on src/Routing/Middleware/RoutingMiddleware.php
> +        $this->app = $app;
The property should be declared, makes phpstan sad without it.

2017-05-12 19:59 UTC, markstory commented on src/Routing/Router.php
> +    public static function getRouteBuilder($path, array $options = [])
Sure.

2017-05-12 19:59 UTC, markstory commented on src/Routing/Middleware/RoutingMiddleware.php
> +        $this->app = $app;
Whoops.

2017-05-15 06:49 UTC, robertpustulka commented on src/Http/ServerRequestFactory.php
> +            $uri = $uri->withHost('localhost');
:+1:

2017-05-21 16:10 UTC, merged