[RFC] Add TableSchemaInterface
cakephp/cakephp pull request #10691
Opened 2017-05-24 11:06 UTC by robertpustulka

Following https://github.com/cakephp/cakephp/pull/10668#issuecomment-302897784

The idea here is to add an interface for `TableSchema` with commonly used methods. I'm wondering if we should add all methods to the interface or are there any specific ones?

There are some Connection related SQL methods. I'm wondering maybe these could be placed in another interface?

Also there are some legacy getter methods without the `get*` prefix. Should we add the "correct" ones to the interface for consistency (getFoo/setFoo) and deprecate the old ones?

I've started with splitting another combined getter/setter for colum type.

2017-05-24 19:11 UTC, markstory commented
New methods look good. Adding an interface for the methods that we rely on internally would be good as well. I don't know if many plugins would implement the SQLy methods though.

2017-05-25 11:09 UTC, thinkingmedia commented on src/Database/Schema/TableSchema.php
> +     * @return array SQL to add the constraints.
thank you :)

2017-05-25 11:11 UTC, robertpustulka commented
@markstory We could have something like `SqlGeneratorInterface` apart from `TableSchemaInterface`. Core `TableSchema` would implement both of them, but plugins could opt-out from generating sql.

2017-05-26 01:25 UTC, markstory commented
@robertpustulka That could work well. Perhaps we can use cakephp/elasticsearch as the second implementation of the `TableSchemaInterface`?

2017-05-26 06:53 UTC, robertpustulka commented
I've added a `SchemaInterface` to `Cake\Datasource` namespace. Unfortunetally there's already a `TableSchemaInterface` which actually looks more like a table schema decorator of some sort. It's used in fixtures. I'm wondering if we could rename it so the `TableSchemaInterface` name would be free in 4.0.

2017-05-26 08:52 UTC, lorenzo commented
> There are some Connection related SQL methods. I'm wondering maybe these could be placed in another interface?

This makes sense to me

2017-05-26 20:28 UTC, markstory commented on src/Database/Schema/TableSchema.php
> +     * @return array|null Column data or null.
Couldn't these be `{@inheritDoc}` now?

2017-05-29 10:05 UTC, robertpustulka commented
I've split the interface into the one with general datasource methods and database specific methods. NoSQL datasources don't need to implement some of the methods.

I've also deprecated datasource `TableSchemaInterface` in favour of database `TableSchemaAwareInterface` which declares a getter and a setter for table schema.

2017-05-29 20:47 UTC, lorenzo commented
Changes look great!

2017-05-30 01:11 UTC, markstory requested changes
Author tags need to be removed.

2017-05-30 01:11 UTC, markstory commented on src/Database/Schema/TableSchemaInterface.php
> + * @author Robert Pustułka <r.pustulka@robotusers.com>
Could this be removed?

2017-05-30 05:27 UTC, robertpustulka commented on src/Database/Schema/TableSchemaInterface.php
> + * @author Robert Pustułka <r.pustulka@robotusers.com>
OK, I missed that - it's been added by the IDE.

2017-05-31 01:57 UTC, markstory approved these changes

2017-05-31 01:57 UTC, merged