Fix issue 10678
cakephp/cakephp pull request #10690
Opened 2017-05-24 03:24 UTC by rchavik

See #10678

2017-05-24 03:36 UTC, ADmad requested changes

2017-05-24 03:36 UTC, ADmad commented on src/Routing/RouteBuilder.php
> +            $path = '/' . $params['path'];
The slash should be added only if doesn't already exist. For e.g. my plugin already sets the path with starting slash https://github.com/ADmad/CakePHP-HybridAuth/blob/master/config/routes.php#L13

2017-05-24 03:48 UTC, rchavik commented on src/Routing/RouteBuilder.php
> +            $path = ($params['path'][0] === '/' ? '' : '/') . $params['path'];
too convoluted?

2017-05-24 04:04 UTC, ADmad commented on src/Routing/RouteBuilder.php
> +            $path = ($params['path'][0] === '/' ? '' : '/') . $params['path'];
Maybe `$path = $params['path'][0] !== '/' ?: '/' . $params['path']`?

2017-05-24 04:14 UTC, rchavik commented on src/Routing/RouteBuilder.php
> +            $path = ($params['path'][0] === '/' ? '' : '/') . $params['path'];
hmm, wouldn't that cause `true` (casted to `1`) to be prepended?

2017-05-24 04:19 UTC, rchavik commented on src/Routing/RouteBuilder.php
> +            $path = ($params['path'][0] === '/' ? '' : '/') . $params['path'];
$ git diff

```diff
diff --git a/src/Routing/RouteBuilder.php b/src/Routing/RouteBuilder.php
index a94d27f..11f5417 100644
--- a/src/Routing/RouteBuilder.php
+++ b/src/Routing/RouteBuilder.php
@@ -613,7 +613,9 @@ class RouteBuilder
         }
         $name = Inflector::underscore($name);
         if (isset($params['path'])) {
-            $path = ($params['path'][0] === '/' ? '' : '/') . $params['path'];
+            debug($params['path']);
+            $path = $params['path'][0] !== '/' ?: '/' . $params['path'];
+            debug($path);
             unset($params['path']);
         } else {
             $path = '/' . $name;
```

```
$ vendor/bin/phpunit --stderr --filter DotIn 
PHPUnit 5.7.20 by Sebastian Bergmann and contributors.

F                                                                   1 / 1 (100%)/src/Routing/RouteBuilder.php (line 616)
########## DEBUG ##########
'v1.0'
###########################
/src/Routing/RouteBuilder.php (line 618)
########## DEBUG ##########
true
###########################


Time: 896 ms, Memory: 96.75MB

There was 1 failure:

1) Cake\Test\TestCase\Routing\RouteBuilderTest::testPathWithDotInPrefix
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'/admin/api/v1.0'
+'/admin/api1'

/home/rachman/sites/croogo3.dev/vendor/cakephp/cakephp/tests/TestCase/Routing/RouteBuilderTest.php:363
/home/rachman/sites/croogo3.dev/vendor/cakephp/cakephp/src/Routing/RouteBuilder.php:701
/home/rachman/sites/croogo3.dev/vendor/cakephp/cakephp/src/Routing/RouteBuilder.php:627
/home/rachman/sites/croogo3.dev/vendor/cakephp/cakephp/tests/TestCase/Routing/RouteBuilderTest.php:369
/home/rachman/sites/croogo3.dev/vendor/cakephp/cakephp/src/Routing/RouteBuilder.php:701
/home/rachman/sites/croogo3.dev/vendor/cakephp/cakephp/src/Routing/RouteBuilder.php:627
/home/rachman/sites/croogo3.dev/vendor/cakephp/cakephp/tests/TestCase/Routing/RouteBuilderTest.php:370

FAILURES!
Tests: 1, Assertions: 1, Failures: 1.
```

2017-05-24 19:24 UTC, markstory commented on src/Routing/RouteBuilder.php
> +        if (isset($params['path'])) {
What if its `false`. The next line will fail.

2017-05-24 19:24 UTC, markstory commented on src/Routing/RouteBuilder.php
> +            $path = ($params['path'][0] === '/' ? '' : '/') . $params['path'];
If the developer is passing a path, they can just do the right thing. I don't think we should be forcing a `/` on people.

2017-05-25 04:29 UTC, markstory approved these changes
Looks good to me.

2017-05-25 04:29 UTC, markstory commented on src/Routing/RouteBuilder.php
> +            unset($params['path']);
:+1: much simpler now.

2017-05-25 04:30 UTC, markstory requested changes
API docs need to be updated. Sorry for missing that earlier.

2017-05-25 04:30 UTC, markstory commented on src/Routing/RouteBuilder.php
> +            unset($params['path']);
This new option should be added to the doc block.

2017-05-26 01:26 UTC, markstory approved these changes

2017-05-26 01:26 UTC, merged