Cake 2.x - Some fix into Paginator component for order / sort classic sintax
cakephp/cakephp pull request #10698
Opened 2017-05-26 18:13 UTC by lucasferreira

Hi folks,

I've noted that classic array "order" aren't work in pagination (CakePHP 2.x):

```php
$this->Paginator->settings['Post'] = array(
  'order' => array('Post.created DESC', 'Post.id ASC') // <--- this doesn't works
);

$items = $this->Paginator->paginate('Post');
```

In my test only this kind of syntax are working:

```php
'order' => array('Post.created' => 'DESC', 'Post.id' => 'ASC') // this works
'order' => 'Post.created DESC, Post.id ASC' // with string also works

'order' => array('Post.created DESC', 'Post.id ASC') // <--- this doesn't works but with this PR will ;)
```

So this pull request has a fix to support all kind of order by syntax, link find() model method does.

Thanks ;)

2017-05-26 20:18 UTC, markstory commented
Could we get tests to cover the new functionality that is being added?

2017-05-26 21:42 UTC, lucasferreira commented
Shure @markstory 

I've added to this PR some simple tests to ensure this _classic array order_ behavior.

What do you think now?

2017-05-27 00:18 UTC, markstory commented
Looking​ good. I will look into why the tests on 2.next are failing.

2017-05-29 12:36 UTC, lucasferreira commented
I don't know if it helps, but here all tests passed:

![pg_tests_ok](https://cloud.githubusercontent.com/assets/234495/26550031/452661fe-4452-11e7-9da2-b56200af3370.png)

2017-05-29 16:09 UTC, markstory commented
Thanks. But we need tests passing in our CI system before we merge.

2017-05-30 15:15 UTC, ravage84 requested changes

2017-05-30 15:15 UTC, ravage84 commented on lib/Cake/Test/Case/Controller/Component/PaginatorComponentTest.php
> +		/* CLASSIC */
If we add comments, they should be a bit more expressive/verbose. Otherweise they aren't much of help.

2017-05-30 20:32 UTC, lucasferreira commented on lib/Cake/Test/Case/Controller/Component/PaginatorComponentTest.php
> +		/* CLASSIC */
Hi @ravage84, can I remove the comments?

2017-05-31 01:39 UTC, markstory commented on lib/Cake/Test/Case/Controller/Component/PaginatorComponentTest.php
> +		/* CLASSIC */
> can I remove the comments?

That would be great.

2017-05-31 11:34 UTC, lucasferreira commented on lib/Cake/Test/Case/Controller/Component/PaginatorComponentTest.php
> +		/* CLASSIC */
Done ;)

2017-06-02 12:53 UTC, dereuromark commented
Looks like unrelated fails. I restarted the build.

2017-06-14 04:13 UTC, merged