Fix type static string and make const
cakephp/cakephp pull request #10735
Opened 2017-06-07 16:02 UTC by mehdi-fathi

Fix type static string and make const and change name of var for make better code.

2017-06-07 16:14 UTC, markstory commented on src/View/View.php
> +    public $uuIds = [];
This is a breaking change. You cannot rename public properties.

2017-06-07 16:15 UTC, markstory requested changes
You have breaking changes right now. The public property change needs to be removed for this to be mergeable.

2017-06-07 16:15 UTC, markstory commented on src/View/View.php
> +                        $defaultPath = $paths[0] . ucfirst(static::TYPE_ELEMENT) . DIRECTORY_SEPARATOR;
Adding a function call adds overhead. Why not add a constant with the appropriate value?

2017-06-07 16:15 UTC, markstory commented on src/View/View.php
> +                        $defaultPath = $paths[0] . ucfirst(static::TYPE_ELEMENT) . DIRECTORY_SEPARATOR;
Perhaps `NAME_ELEMENT`?

2017-06-07 16:25 UTC, mehdi-fathi commented on src/View/View.php
> +                        $defaultPath = $paths[0] . ucfirst(static::TYPE_ELEMENT) . DIRECTORY_SEPARATOR;
Yes NAME_ELEMENT is better than

2017-06-09 11:22 UTC, ADmad requested changes

2017-06-09 11:22 UTC, ADmad commented on src/View/View.php
> + * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
Undo these http to https changes. This header needs to stay consistent across all files.

You can make a separate PR to change it for all files if you want.

2017-06-09 11:27 UTC, mehdi-fathi commented on src/View/View.php
> + * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
Yes i think a separate commit is good for this work.Because of almost all of file's url cakephp.org has this problem.

2017-06-09 14:37 UTC, markstory commented
Do you have a scenario where you needed to change the constants?

2017-06-09 14:45 UTC, mehdi-fathi commented
@markstory Actually i don't have.But it better than former code.When you use a string can will be use more than one time.Why it be not a constants.

2017-06-09 14:58 UTC, markstory commented
I wasn't arguing for not having constants. Just wondering what your usecase/motivation was to change this :smile:

2017-06-09 14:58 UTC, markstory approved these changes

2017-06-09 15:33 UTC, mehdi-fathi commented
Nothing.just a name of element constant for access another place.maybe there is no need.

2017-06-09 22:13 UTC, merged