Make test method's request
cakephp/cakephp pull request #10762
Opened 2017-06-12 08:16 UTC by mehdi-fathi

Make test method's request and fix some of problems in Request.php

2017-06-12 09:51 UTC, robertpustulka commented on src/Http/Client/Request.php
> +// @deprecated Add backwards compact alias.
I think it's short for backwards compat*ibility*

2017-06-12 09:52 UTC, robertpustulka commented on tests/TestCase/Http/Client/RequestTest.php
>          $this->assertSame($request, $request, 'Should return self');
This should be fixed to assert against `$result`

2017-06-12 11:57 UTC, markstory commented on src/Http/Client/Request.php
> +// @deprecated Add backwards compact alias.
It is.

2017-06-12 12:00 UTC, markstory requested changes

2017-06-12 12:00 UTC, markstory commented on src/Http/Client/Request.php
> + * @license       https://www.opensource.org/licenses/mit-license.php MIT License
You don't need the www on the https URLs.

2017-06-12 12:00 UTC, markstory commented on tests/TestCase/Http/Client/RequestTest.php
> +        $this->assertEquals(json_encode($data), $request->body());
This looks like a test that could benefit from a [dataprovider](https://phpunit.de/manual/current/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.data-providers).

2017-06-12 15:39 UTC, mehdi-fathi commented on tests/TestCase/Http/Client/RequestTest.php
>          $this->assertSame($request, $request, 'Should return self');
Yes exacly

2017-06-13 00:56 UTC, markstory commented on tests/TestCase/Http/Client/RequestTest.php
> +        $this->assertContains($request->getMethod(), $this->methods);
Wouldn't it be more accurate to check that the method matches exactly? Right now the test would continue to pass even if the request method was transposed to another valid method that wasn't requested.

2017-06-13 05:44 UTC, mehdi-fathi commented on tests/TestCase/Http/Client/RequestTest.php
> +        $this->assertContains($request->getMethod(), $this->methods);
It make no difference.but you are right assertcontains isn't suitable here.

2017-06-14 02:15 UTC, merged

2017-06-15 09:23 UTC, ravage84 commented on src/Http/Client/Request.php
> +// @deprecated Add backwards compact alias.
I would recommend to write out the word compatibility in the future.