Fix error when default value is reported as CURRENT_TIMESTAMP() by mysql
cakephp/cakephp pull request #10830
Opened 2017-06-27 09:06 UTC by kurrestahlberg

My database version (mysqld  Ver 10.2.6-MariaDB for osx10.12 on x86_64 (Homebrew)) reports the default value current_timestamp with parenthesis (like so: ``` `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()```) which confuses the CakePHP mysql driver to think it is a string and that leads to the following error when running tests: 
```
2017-06-27 11:51:16 Error: Fixture creation for "ad_campaigns" failed "SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at'"
PHP Warning:  Fixture creation for "ad_campaigns" failed "SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'updated_at'" in /Users/kurre/mcn/nativeflow/Vendor/cakephp/cakephp/lib/Cake/TestSuite/Fixture/CakeTestFixture.php on line 244
```
This patch will allow for the parenthesis and that fixes my issue (#10829)

I am unsure how to write a test for this as it seems to be database version specific issue.

2017-06-27 16:26 UTC, markstory requested changes
Any chance we could get an updated unit test covering this scenario?

2017-06-27 16:27 UTC, markstory commented
If you need help with the tests let me know. I'm happy to help out with them :smile:

2017-06-29 10:32 UTC, kurrestahlberg commented
Yeah, if you could help that would be great. I've looked at the tests that currently are there in the 2.x branch and it tests only that the default value is ignored, but what the default is reported as cannot be IMO changed.

Is there a way to custom build (or alter) whatever describe()'s input without hacking Model?

2017-07-02 15:07 UTC, markstory commented
I took a look and you're right that testing this would only be possible by using mocks to muck around with the query results, which I'd rather not have.

2017-07-02 15:08 UTC, merged