3.next add new paramater to testing helper
cakephp/cakephp pull request #10927
Opened 2017-07-19 21:43 UTC by viraj-khatavkar

Currently, the `assertResponseContains` method accepts only two parameters for assertion against the content and message.

There have been some use-cases while testing where I needed to ignore the case for asserting the content on pages where the content has been capitalized by CSS. `PHPUnit` gives support for ignoring the content case with a `ignoreCase` parameter. I have added support for the same in this test method.

2017-07-19 23:10 UTC, markstory requested changes

2017-07-19 23:10 UTC, markstory commented on src/TestSuite/IntegrationTestCase.php
>      {
This isn't backwards compatible right now. You need to make ignoreCase the last parameter.

2017-07-19 23:12 UTC, viraj-khatavkar commented on src/TestSuite/IntegrationTestCase.php
> +     * @param bool   $ignoreCase A flag to check whether we should ignore case or not.
It matches, is it because of the space?

2017-07-19 23:13 UTC, viraj-khatavkar commented on src/TestSuite/IntegrationTestCase.php
>      {
Then I would have to always specify the message parameter also. But I agree that we need it to be backward compatible. I'll amend it.

2017-07-19 23:15 UTC, markstory commented on src/TestSuite/IntegrationTestCase.php
>      {
Another option would be to parameter sniff based on types, but that gets awkward if more parameters are added later.

2017-07-19 23:19 UTC, viraj-khatavkar commented on src/TestSuite/IntegrationTestCase.php
>      {
Let's keep it as the last parameter for now. Would I propose making another pull request with `ignoreCase` as the second parameter for the 4.0 branch?

2017-07-20 06:44 UTC, HavokInspiration commented on src/TestSuite/IntegrationTestCase.php
> +     * @param bool   $ignoreCase A flag to check whether we should ignore case or not.
@viraj-khatavkar I think so. We never align docblocks parameters as they can become quickly out of sync.

2017-07-20 13:22 UTC, viraj-khatavkar commented
@markstory Do I need to make any other amends, or is this fine?

2017-07-20 13:23 UTC, viraj-khatavkar commented on src/TestSuite/IntegrationTestCase.php
> +     * @param bool   $ignoreCase A flag to check whether we should ignore case or not.
@HavokInspiration Fair enough!

2017-07-20 14:00 UTC, saeideng commented
tests on php 7.0 failed

2017-07-20 17:36 UTC, markstory approved these changes

2017-07-20 17:36 UTC, merged