Add a getter for Response::charset
cakephp/cakephp pull request #10942
Opened 2017-07-24 20:29 UTC by cleptric

I also smuggeld some typo fixes into this PR

2017-07-24 20:37 UTC, cleptric commented on src/Http/Response.php
> +     * @deprecated 3.5.0 Use getCharset()/withCharset() instead.
Should this be `3.4.0/3.5.0` or is it fine this way?

2017-07-24 20:38 UTC, dereuromark commented on src/Http/Response.php
> +     * @deprecated 3.5.0 Use getCharset()/withCharset() instead.
It can only accept one number, we either chose the lowest or highest.

2017-07-25 00:07 UTC, markstory commented
Looks good. I will get the phpstan errrors fixed up.

2017-07-25 04:04 UTC, ADmad requested changes

2017-07-25 04:04 UTC, ADmad commented on phpstan.neon
> +        - '#Function mcrypt_[a-zA-Z0-9_]+ not found#'
You need to revert this extra ignores you added. They are causing the travis build to fail since these methods are actually available there.

2017-07-25 10:26 UTC, cleptric commented
Phpstan is happy now 😀

2017-07-25 17:56 UTC, merged