Added support for numeric nested fields type, isRequired, val and att…
cakephp/cakephp pull request #11004
Opened 2017-08-06 14:24 UTC by lilHermit

…ributes

    Updated tests too
See #11003

2017-08-06 14:56 UTC, ADmad requested changes

2017-08-06 14:56 UTC, ADmad commented on src/View/Form/ArrayContext.php
> +        } else {
`else` is not required since there is a `return` in `if` block.

2017-08-06 14:56 UTC, ADmad commented on src/View/Form/ArrayContext.php
> +     *
Please add an example of input and output for easier understanding.

2017-08-06 15:17 UTC, lilHermit commented
Do you think the following it more efficient?!

```php
protected function stripNesting($field)
{
    return preg_replace('/\.\d/','',$field);
}
```

2017-08-07 00:57 UTC, markstory commented
@lilHermit It does look much simpler.

2017-08-07 08:13 UTC, lilHermit commented
@markstory definitely simpler but my concern was (and the reason I used implode/explode) keys starting with numeric will break for example `users.0.9tags` becomes `userstags`

I've have now tweaked the regex to fix this

2017-08-12 01:50 UTC, merged