3.x APCu Cache Engine Improvements
cakephp/cakephp pull request #11290
Opened 2017-10-07 01:45 UTC by inoas

This super-cedes https://github.com/cakephp/cakephp/pull/11279

2017-10-07 01:48 UTC, inoas commented
Hmm... warn() will not report the correct file etc... right?

2017-10-07 03:49 UTC, ADmad requested changes

2017-10-07 03:49 UTC, ADmad commented on src/Cache/CacheEngine.php
> +    private function warn($message)
We don't use privates.

2017-10-07 15:44 UTC, markstory commented on src/Cache/Engine/ApcuEngine.php
> + * @since         1.2.0
Needs to be updated

2017-10-07 23:30 UTC, inoas commented
What can/should I do about tests failing because they try to read non-existing apcu keys?
https://travis-ci.org/cakephp/cakephp/jobs/284853635

2017-10-07 23:39 UTC, inoas commented
Is this a good solution? https://stackoverflow.com/questions/32884788/phpunit-assert-e-user-warning-is-generated-as-expected-without-ending-a-test

2017-10-07 23:43 UTC, saeideng commented
I think you should use `git mv ... `  to moving a file in git

2017-10-08 00:06 UTC, inoas commented
For the diffs on ApcuEngine vs ApcEngine you can take a look here: https://github.com/cakephp/cakephp/pull/11290/commits/944d57b4c583fee5af1737bcbc02a223e028ff25

2017-10-08 22:20 UTC, saeideng commented
maybe needs `3.next` branch 

`src/Cache/Engine/ApcEngine_CLASS_ALIAS.php`

2017-10-08 22:33 UTC, dereuromark commented on src/Cache/CacheEngine.php
> +        if ($this->config('disableWarningsOnFailures') !== true) {
Shouldnt you rather bail early to avoid nesting?

2017-10-09 15:20 UTC, closed without merging