Fix cache as dependency for ORM
cakephp/cakephp pull request #11612
Opened 2018-01-08 18:55 UTC by dereuromark

Resolves https://github.com/sergeyklay/php-orm-benchmark/pull/6
By default cache must be enabled on production systems, otherwise it will completely kill the ORM performance.
Thus this should be a require dependency.
The readme even states the direct use of Cache.

2018-01-08 19:50 UTC, saeideng requested changes

2018-01-08 19:50 UTC, saeideng commented on src/ORM/composer.json
> +        "cakephp/cache": "^3.0.0",
I guess you need this in the 
`cakephp/datasource`
`cakephp/database`

2018-01-08 20:03 UTC, dereuromark commented
@saeideng Thank you, good find!

2018-01-08 20:11 UTC, lorenzo commented
This package was left out on purpose and only set as a suggestion, what changed?

2018-01-08 20:12 UTC, lorenzo commented
I guess it is not super important, but ideally in the future we should conform to some sort of interface and let the user chose the caching library

2018-01-08 20:13 UTC, dereuromark commented
Yes, ideally we should interface contract here :)
We can still do that probably in a BC way, I think.

PS: We should also have a tool for finding the dependencies to other use statements. 
Right now it is a lot of guessing from our side, since we do not use those splits, and there is also no tooling around it for split unit testing.

2018-01-08 20:14 UTC, lorenzo commented
Can you change the readme and add some notes about configuring he cache? I think by default the cache folder will not exist, so it would make sense to show how to configure it to use a sys tmp folder

2018-01-08 20:19 UTC, dereuromark commented
What would be needed using the split setup?
If you have an idea, you can add your commit on top.

2018-01-09 10:22 UTC, lorenzo commented
Can you use the code from the php orm benchmarks repo?

2018-01-09 10:39 UTC, dereuromark commented
I wonder if we should add the note that by default even with `'cacheMetadata' => true` enabled it will use a NullLogger and not cache at all.

2018-01-11 08:54 UTC, dereuromark commented
Does it look complete now?

2018-01-11 21:02 UTC, merged