Milestone 10918
cakephp/cakephp pull request #11755
Opened 2018-02-25 00:48 UTC by xaphalanx

Collections enhanced to provide a way to appendItem() for a single item, as well as prepend() and prependItem().

2018-02-25 01:20 UTC, dereuromark commented on src/Collection/CollectionInterface.php
> +     * @param string $key Optional key to associate item
|null missing

2018-02-25 03:48 UTC, markstory commented
Moved to 3.6 and linked to the original issue.

2018-02-25 03:52 UTC, dereuromark commented on src/Collection/CollectionInterface.php
> +     * @return Collection
Shouldnt this be \Cake\Collection\CollectionInterface ?

2018-02-25 14:31 UTC, xaphalanx commented
Thank you dereuromark, I'll update the doc blocks.

2018-02-26 23:45 UTC, burzum commented
I like this PR but it also is a good example for this discussion. :) https://github.com/cakephp/cakephp/issues/11735 When people implement CollectionInterface their code will now probably break, unlikely but I just want to bring this up.

2018-02-27 20:34 UTC, robertpustulka commented
We added methods to the `CollectionInterface` before (https://github.com/cakephp/cakephp/commit/600663e75ad643aa6980cde780babe564e24f78c) so I don't think we should worry about that now and instead make a decision how to do it properly in the future (#11735).

2018-03-26 08:20 UTC, lorenzo requested changes

2018-03-26 13:32 UTC, xaphalanx commented on src/Collection/CollectionTrait.php
> +        return new Collection($values);
Making that change causes this test to fail:

```php
        $collection = new Collection([1, 2, 3]);
        $combined = $collection->prependItem('a');
        $this->assertEquals(['a', 1, 2, 3], $combined->toArray());
```

```text
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => 'a'
-    1 => 1
-    2 => 2
-    3 => 3
+    0 => 1
+    1 => 2
+    2 => 3


```

2018-03-26 13:35 UTC, lorenzo commented on src/Collection/CollectionTrait.php
> +        return new Collection($values);
Yes, that is expected. You wan to call `toList()` instead. It will be the same for `append` when the keys are repeated.

2018-03-26 13:37 UTC, lorenzo commented on src/Collection/CollectionTrait.php
> +        return new Collection($values);
I general, I think we should hide `toArray()` as much as possible... maybe deprecate it? The presence of keys causes a big amount of issues.

2018-03-26 14:06 UTC, xaphalanx commented on src/Collection/CollectionTrait.php
> +        return new Collection($values);
I can see that if you call prependItem you'll need to know if you have keys or not and call the correct thing to get the collection changed into an array correctly. With this set of interfaces and count() added maybe there will be few reasons to turn it back into an array once it is a collection.

2018-03-26 15:26 UTC, xaphalanx commented on src/Collection/CollectionTrait.php
> +        return new Collection($values);
That's messed up for some reason it can't see my change to the file in the pull request.

2018-03-26 15:38 UTC, lorenzo approved these changes

2018-03-26 16:33 UTC, lorenzo approved these changes

2018-03-27 14:53 UTC, merged