Fixed return type (array) #11795
cakephp/cakephp pull request #12065
Opened 2018-05-10 19:23 UTC by odan

This change ensures that `fetchAll` always returns an array.

2018-05-10 19:45 UTC, dereuromark requested changes

2018-05-10 19:45 UTC, dereuromark commented on src/Database/Statement/BufferedStatement.php
> +        if ($result = $this->fetch(static::FETCH_TYPE_ASSOC)) {
you shouldnt assign inside condition.

2018-05-10 19:49 UTC, odan commented on src/Database/Statement/BufferedStatement.php
> +        if ($result = $this->fetch(static::FETCH_TYPE_ASSOC)) {
Done

2018-05-10 21:02 UTC, dereuromark commented on src/Database/Statement/BufferedStatement.php
> +
You can use  ?:

2018-05-11 01:14 UTC, markstory commented on src/Database/Statement/StatementDecorator.php
> +     * @return array Result array containing columns and values an an associative array or an empty array if no results
I wonder how likely it is that someone has `=== false` in their code. It might be wise to move this to 3.next for that reason.

2018-05-11 19:43 UTC, markstory commented on src/Database/Statement/BufferedStatement.php
> +
bonus line.

2018-05-11 19:43 UTC, markstory commented on src/Database/Statement/StatementDecorator.php
> +
Here too.

2018-05-11 21:04 UTC, dereuromark commented on src/Database/Statement/BufferedStatement.php
> +
No, I mean the short ternary form: `return $result ?: [];`. Cleaner since you do not repeat it.

2018-05-12 23:18 UTC, merged