Remove duplicate test code.
cakephp/cakephp pull request #12589
Opened 2018-09-23 20:12 UTC by ADmad

2018-09-23 20:13 UTC, ADmad commented on tests/TestCase/Database/QueryTest.php
> -        $query = new Query($this->connection);
The exact same query instance and assertions are done above. So unless I am missing something the removed code was redundant.

2018-09-23 21:02 UTC, saeideng requested changes
its not same 
see `->distinct('author_id')`  and `->distinct(['author_id'])`

2018-09-23 21:09 UTC, dereuromark commented
An inline comment might have clarified this.

2018-09-24 01:04 UTC, markstory commented
Closing for the reason @saeideng mentioned.

2018-09-24 01:04 UTC, closed without merging