Implement PSR7 header methods
cakephp/cakephp pull request #9514
Opened 2016-09-24 04:17 UTC by markstory

Implement the header related method required for the PSR7 ServerRequestInterface. 

I've chosen to make the new methods read from the existing data as with the other changes I've done so far. This should hopefully make the new methods non-destructive to the existing ones.

Refs #9325

2016-09-24 16:59 UTC, lorenzo commented on src/Network/Request.php
> +            $data['_method'] = $this->getHeaderLine('X-Http-Method_Override');
Why does it have an underscore here?

2016-09-24 17:00 UTC, lorenzo commented on src/Network/Request.php
> +            $data['_method'] = $this->getHeaderLine('X-Http-Method_Override');
I meant, there is an underscore instead of a hyphen in the header name.

2016-09-24 17:03 UTC, lorenzo commented on src/Network/Request.php
> +        return array_key_exists($name, $this->_environment);
I think isset is more appropriate here. At least that is what the get function is using

2016-09-24 17:04 UTC, lorenzo requested changes

2016-09-24 23:20 UTC, markstory commented on src/Network/Request.php
> +            $data['_method'] = $this->getHeaderLine('X-Http-Method_Override');
Because I'm a muppet.

2016-09-24 23:23 UTC, markstory commented on src/Network/Request.php
> +        return array_key_exists($name, $this->_environment);
Fixed.

2016-09-25 04:09 UTC, merged

2016-09-25 04:09 UTC, lorenzo commented
Great job @markstory

2016-09-25 15:53 UTC, markstory commented
Uri methods are next!