Add missing HTTP status codes/messages
cakephp/cakephp pull request #9523
Opened 2016-09-26 13:40 UTC by ravage84

Add status codes from [Zend/Diactoros](https://github.com/zendframework/zend-diactoros/blob/215f47a73fb2a7f2d33230a3e23658acae234035/src/Response.php#L32-L96) and [httpstatuses.com](https://httpstatuses.com/).

Refers https://github.com/cakephp/cakephp/issues/9516#issuecomment-249367130

2016-09-26 13:45 UTC, chinpei215 commented on src/Network/Response.php
> +        511 => 'Network Connect Timeout Error',
599?

2016-09-26 13:56 UTC, ravage84 commented on src/Network/Response.php
> +        511 => 'Network Connect Timeout Error',
Darn! Copy-Pasta Error :imp:

2016-09-26 18:19 UTC, inoas commented on src/Network/Response.php
> +        499 => 'Client Closed Requet',
typo

2016-09-26 18:20 UTC, inoas commented on src/Network/Response.php
>          504 => 'Gateway Time-out',
Timeout

2016-09-26 18:24 UTC, ravage84 commented on src/Network/Response.php
>          504 => 'Gateway Time-out',
I did not want to change the existing ones. Can be done in another PR...

2016-09-26 20:05 UTC, markstory commented on src/Network/Response.php
> +        506 => 'Variant Also Negotiates',
Missing a comma on line 97.

2016-09-26 20:06 UTC, markstory requested changes

2016-09-27 13:53 UTC, ADmad commented
Failing test seems relevant to this change.

2016-09-27 13:59 UTC, ADmad commented
I'll fix the test case post merge.

2016-09-27 13:59 UTC, merged

2016-09-27 14:02 UTC, ravage84 commented
@ADmad you are too fast, just pushed the updated test code ;-)

2016-09-27 14:15 UTC, inoas commented
306 is wrong. I fixed it here: https://github.com/cakephp/cakephp/pull/9528
Also I carried together 65 codes. One is missing in this PR.

2016-09-27 14:17 UTC, inoas commented
`421 => 'Misdirected Request', // RFC7540, Section 9.1.2` is missing in this PR, I fixed it here: #9528