3.x PaginatorHelper::defaultScope() and 'scope' / Consistency with PaginatorComponent
cakephp/cakephp pull request #9564
Opened 2016-10-03 21:20 UTC by inoas

Ref: https://github.com/cakephp/cakephp/issues/9211

2016-10-03 21:24 UTC, inoas commented
I hope it is close to what you had in mind @markstory.

2016-10-03 21:27 UTC, dereuromark commented on src/View/Helper/PaginatorHelper.php
> +    private function _deprecateModelOption(array $options)
Protected please.

2016-10-04 03:12 UTC, markstory commented
Moving to 3.4 and retargeting to 3.next as this changes protected properties that could break userland code.

2016-10-04 03:15 UTC, markstory commented on src/View/Helper/PaginatorHelper.php
> +     * @deprecated use defaultScope() instead.
Should have a version number here (3.4.0)

2016-10-04 03:15 UTC, markstory commented on src/View/Helper/PaginatorHelper.php
> +            $options['scope'] = $options['model'];
Perhaps scope should only be written if model is defined and scope is *not* defined?

2016-10-04 03:15 UTC, markstory commented on tests/TestCase/View/Helper/PaginatorHelperTest.php
> +        $result = $this->Paginator->counter('Showing {{page}} of {{pages}} {{scope}}');
Does the old model variable still work?

2016-10-04 08:39 UTC, ADmad requested changes

2016-10-04 08:39 UTC, ADmad commented on src/View/Helper/PaginatorHelper.php
> +        if (!empty($this->_config['options']['scope'])) {
To maintain BC using old key `model` should still be possible.

2016-10-04 08:39 UTC, ADmad commented on src/View/Helper/PaginatorHelper.php
> +        $url = $this->generateUrl($url, $options['scope']);
To maintain BC using old key `model` should still be possible.

2016-10-04 14:08 UTC, inoas commented on tests/TestCase/View/Helper/PaginatorHelperTest.php
> +        $result = $this->Paginator->counter('Showing {{page}} of {{pages}} {{scope}}');
Fixed that in a new commit.

2016-10-04 14:08 UTC, inoas commented on src/View/Helper/PaginatorHelper.php
> +     * @deprecated use defaultScope() instead.
Fixed in new commit.

2016-10-04 15:58 UTC, inoas commented
If you want me to I can copy the old tests in the testcases as well.

2016-10-04 16:11 UTC, markstory commented on src/View/Helper/PaginatorHelper.php
> +            $options['scope'] = $options['model'];
How would userland code break on a parent call for a method that doesn't exist yet?

2016-10-04 16:19 UTC, inoas commented on src/View/Helper/PaginatorHelper.php
> +            $options['scope'] = $options['model'];
Say someone has written code like:

```php
$this->Paginator->options(['model' => 'Client', 'scope' => 'ThinClient']);
```

... having overloaded Paginator with his own PaginatorHelper which extends upon the core PaginatorHelper.
Here the meaning of scope is/was a different.

I can change it to B, if you say so. I am just not sure it is entirely better.

2016-10-05 01:30 UTC, markstory commented on src/View/Helper/PaginatorHelper.php
> +            $options['scope'] = $options['model'];
We don't make promises around backwards-compatibility if people override methods and add arguments/options.

2016-10-06 13:02 UTC, ravage84 requested changes

2016-10-06 13:02 UTC, ravage84 commented on src/View/Helper/PaginatorHelper.php
> +     * @return array Array of options
Either here or in the long description of this method you could/should document the intent a little bit more.
A one liner should suffice. What is been done to the model option to deprecate it?

2016-10-06 13:02 UTC, ravage84 commented on tests/TestCase/View/Helper/PaginatorHelperTest.php
> +        // Deprecated 3.4.0:
"Deprecated as of 3.4.0"

2017-04-29 18:37 UTC, dereuromark commented
Is this still interesting to be finished up? @inoas

2017-04-30 21:54 UTC, inoas commented
I really do want to finish the few PRs I have opened yet. If you want to close them as part of clean up - feel free, I will get back to them as soon as project pressure is less.

2017-09-20 22:32 UTC, dereuromark commented
This would now be able to go into 3.6
Are you still interested in finishing it up? Otherwise we should close.

2017-09-20 23:13 UTC, inoas commented
Do I see correctly that aside the merge conflict and some CS checks the unit tests already run?

I think I can pick this up the coming weeks (after doing some more work on TwigView) and finish this in 3.6 so that the deprecated name can be removed in 4.0...

2019-01-06 18:13 UTC, closed without merging