Add escape false to PaginationHelper
cakephp/cakephp pull request #9569
Opened 2016-10-04 13:22 UTC by dereuromark

Resolves https://github.com/cakephp/cakephp/issues/9310

First draft of yesterday evening.
If the idea is accepted I can add some tests later on.

2016-10-04 13:50 UTC, markstory commented on src/View/Helper/PaginatorHelper.php
> +            'fullBase' => $full
This means you can never have URL parameters with these names.

2016-10-04 13:51 UTC, dereuromark commented on src/View/Helper/PaginatorHelper.php
> +            'fullBase' => $full
So we need to use a separate $config here then for the url options only.

2016-10-04 16:13 UTC, markstory requested changes
Looks good, you need some tests though.

2016-10-05 07:27 UTC, dereuromark commented
Tests added.

2016-10-05 08:18 UTC, merged

2016-10-05 08:18 UTC, lorenzo commented
Good job!