Refactor association traits
cakephp/cakephp pull request #9594
Opened 2016-10-10 14:17 UTC by lorenzo

This moves the logic in `SelectableAssociationTrait` and `ExternalAssociationTrait` into separate classes that are used as collaborators in the association classes.

I feel this makes the code more readable and easier to grep, as from previous experience, jumping in between the traits was quite a bad experience.

2016-10-10 15:05 UTC, inoas requested changes

2016-10-10 15:05 UTC, inoas commented on src/ORM/Association.php
> +        $strategy = isset($options['strategy']) ? $options['strategy'] : $this->strategy();
It seems to also act as a setter and thus the docblock above should educate about that.

2016-10-10 15:10 UTC, dakota commented on src/ORM/Association/ExternalAssociationTrait.php
> -}
Chance that anybody is using this trait?

2016-10-10 16:08 UTC, lorenzo commented on src/ORM/Association/ExternalAssociationTrait.php
> -}
Very low, I have not heard of anyone creating their own associations. In any case, they have the new classes where he same methods live

2016-10-10 16:08 UTC, lorenzo commented on src/ORM/Association.php
> +        $strategy = isset($options['strategy']) ? $options['strategy'] : $this->strategy();
This is not a setter

2016-10-11 01:28 UTC, markstory reviewed
Awesome work @lorenzo :clap:

2016-10-11 01:28 UTC, markstory commented on src/ORM/Association.php
> +        return $strategy === $this::STRATEGY_SELECT;
`static::STRATEGY_SELECT`?

2016-10-11 01:28 UTC, markstory commented on src/ORM/Association/BelongsTo.php
> -    use SelectableAssociationTrait;
:clap:

2016-10-11 01:28 UTC, markstory commented on src/ORM/Association/ExternalAssociationTrait.php
> -}
I think changing internal implementation is ok for a minor release. I doubt anyone ever figured out how to use these traits. I know both @lorenzo and myself have become lost in the maze of methods they create a few times now.

2016-10-11 01:28 UTC, markstory commented on src/ORM/Association/Loader/SelectLoader.php
>   */
Should this class be marked as `@internal` or is it part of the 'public' API for the ORM?

2016-10-11 01:28 UTC, markstory commented on src/ORM/Association/Loader/SelectLoader.php
> +    protected $strategy = 'select';
Is there a constant we should use instead?

2016-10-11 01:28 UTC, markstory commented on src/ORM/Association/Loader/SelectLoader.php
> +        $fetchQuery = $finder()
Kind of nice that we get to reuse the `find()` logic in `Association::find()` now.

2016-10-11 01:28 UTC, markstory commented on src/ORM/Association/Loader/SelectWithPivotLoader.php
> + * Implements the logic for loading an association using a SELECT query and a pivot table
Another `@internal` class?

2016-10-11 07:24 UTC, inoas commented on src/ORM/Association.php
> +        $strategy = isset($options['strategy']) ? $options['strategy'] : $this->strategy();
Sorry I misread.

2016-10-11 08:04 UTC, lorenzo commented on src/ORM/Association/Loader/SelectLoader.php
>   */
I can make it as internal

2016-10-11 08:08 UTC, lorenzo commented
@markstory I marked the classes as internal and added the other suggested changes

2016-10-11 15:17 UTC, markstory commented
Looks good to me :+1:

2016-10-11 19:49 UTC, merged