replaces fieldList with fields
cakephp/cakephp pull request #9639
Opened 2016-10-22 15:38 UTC by thinkingmedia

The `fieldList` option for `newEntity` isn't consistent with other parts of the ORM. Where `fields` is used to select what fields will be used (queries as an example).

This PR deprecates `fieldList` and changes it to `fields`. With `fieldList` support working as before and to be removed at a later date.

2016-10-22 15:44 UTC, dereuromark commented
👍 

out of scope but something we could think about for 3.4+:
https://github.com/cakephp/bake/issues/281#issuecomment-255535477
We need to maybe provide a "fields" way including exceptions for non-whitelisted fields as otherwise you might add fields to forms and don't even notice how they never get persisted until it is too late.

2016-10-22 15:46 UTC, thinkingmedia commented
@dereuromark this wasn't trying to address that issue. It's just a fluke that the issue was opened. I had discussed this on slack a while back.

2016-10-22 15:49 UTC, thinkingmedia commented
@dereuromark if we could include the `fields` whitelist as data attached to the rules/validation events. We would then allow developers to implement their own solutions. (i.e. a validation rule to reject on mismatch posted data and whitelist).

2016-10-22 22:02 UTC, inoas commented
👍

2016-10-22 22:06 UTC, inoas requested changes

2016-10-22 22:06 UTC, inoas commented on src/ORM/Marshaller.php
> +     * - fieldList: (deprecated) use fields instead.
Add version when.

2016-10-22 22:06 UTC, inoas commented on src/ORM/Marshaller.php
> +     * - fields: A whitelist of fields to be assigned to the entity. If not present,
> Also see Entity `$_accessible`.

2016-10-22 22:06 UTC, inoas commented on src/ORM/Marshaller.php
> +        /* @var Entity $entity */
?

2016-10-22 22:06 UTC, inoas commented on src/ORM/Marshaller.php
> +     * - fieldList: (deprecated) use fields instead
Version again

2016-10-22 22:06 UTC, inoas commented on src/ORM/Marshaller.php
> +     * - fields: A whitelist of fields to be assigned to the entity. If not present,
See $_accessible again.

2016-10-22 22:06 UTC, inoas commented on src/ORM/Marshaller.php
> +     * - fieldList: (deprecated) use fields instead
Version again.

2016-10-22 22:06 UTC, inoas commented on src/ORM/Marshaller.php
> +     * - fields: A whitelist of fields to be assigned to the entity. If not present
See accessible again

2016-10-22 22:06 UTC, inoas commented on src/ORM/Marshaller.php
> +     * - fieldList: (deprecated) use fields instead
Version again.

2016-10-22 22:06 UTC, inoas commented on src/ORM/Marshaller.php
> +     * - fields: A whitelist of fields to be assigned to the entity. If not present,
See accessible again.

2016-10-22 22:06 UTC, inoas commented on tests/TestCase/ORM/MarshallerTest.php
> +            'associated' => ['Tags._joinData' => [$fields => ['foo']]]
Could we keep the old and new test alongside and mark the old tests one deprecated (with version)?

2016-10-22 22:06 UTC, inoas commented on tests/TestCase/ORM/MarshallerTest.php
> +                'Tags._joinData' => [$fields => ['active', 'user']],
Could we keep the old and new test alongside and mark the old tests one deprecated (with version)?

2016-10-22 22:06 UTC, inoas commented on tests/TestCase/ORM/MarshallerTest.php
> +            $fields => ['something'],
Could we keep the old and new test alongside and mark the old tests one deprecated (with version)?

2016-10-22 22:06 UTC, inoas commented on tests/TestCase/ORM/MarshallerTest.php
> +                'Users' => [$fields => ['username', 'foo']]
Could we keep the old and new test alongside and mark the old tests one deprecated (with version)?

2016-10-22 22:06 UTC, inoas commented on tests/TestCase/ORM/MarshallerTest.php
> +        $result = $marshall->mergeMany($entities, $data, [$fields => ['id', 'comment']]);
Could we keep the old and new test alongside and mark the old tests one deprecated (with version)?

2016-10-22 22:06 UTC, inoas commented on tests/TestCase/ORM/MarshallerTest.php
> +        $result = $marshall->many($data, [$fields => ['comment', 'user_id']]);
Could we keep the old and new test alongside and mark the old tests one deprecated (with version)?

2016-10-22 22:06 UTC, inoas commented on tests/TestCase/ORM/MarshallerTest.php
> +        $result = $marshall->merge($entity, $data, [$fields => ['title', 'body']]);
Could we keep the old and new test alongside and mark the old tests one deprecated (with version)?

2016-10-22 22:06 UTC, inoas commented on tests/TestCase/ORM/MarshallerTest.php
> +        $result = $marshall->one($data, [$fields => ['title', 'author_id']]);
Could we keep the old and new test alongside and mark the old tests one deprecated (with version)?

2016-10-22 22:06 UTC, inoas commented on tests/TestCase/ORM/MarshallerTest.php
> +            $fields => ['title', 'user'],
Could we keep the old and new test alongside and mark the old tests one deprecated (with version)?

2016-10-22 22:07 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +        /* @var Entity $entity */
type hinting for IDE

2016-10-22 22:17 UTC, thinkingmedia commented
@inoas I don't really want to duplicate the unit tests. The PR has no change in logic so the tests would be identical. Only the name of an option has changed.

When we remove support for `fieldList` then I can remove the data providers. This is kind of a transitional change.

2016-10-23 03:31 UTC, markstory commented on src/ORM/Marshaller.php
> +        /* @var Entity $entity */
Shouldn't it be `EntityInterface`?

2016-10-23 03:31 UTC, markstory commented on src/ORM/Marshaller.php
> +            $options['fields'] = $options['fieldList'];
I am not sure the deprecated option should overwrite the undeprecated one. Perhaps this should be `isset($options['fieldList']) && !isset($options['fields'])`?

2016-10-23 03:31 UTC, markstory commented on src/ORM/Marshaller.php
> +        if (isset($options['fields'])) {
Could `_prepareDataAndOptions()` ensure this key is always set?

2016-10-23 03:31 UTC, markstory commented on src/ORM/Marshaller.php
> +                    $entity->set($field, $properties[$field]);
I'm pretty sure this gets around the potential `$_accessible` issue you @dereuromark were discussing elsewhere in this pull request.

2016-10-23 03:31 UTC, markstory commented on tests/TestCase/ORM/MarshallerTest.php
> +            $fields => ['title', 'user'],
The dataprovider approach is good enough for me.

2016-10-23 13:20 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +        /* @var Entity $entity */
@markstory maybe, I think the function is using methods from Entity and not the interface, but I'll double check.

2016-10-23 13:21 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +            $options['fields'] = $options['fieldList'];
good eye. I'll fix that.

2016-10-27 08:04 UTC, inoas approved these changes

2016-11-01 14:18 UTC, dereuromark commented on src/ORM/Marshaller.php
> +            $options['fields'] = $options['fieldList'];
This is probably the only thing left right?
Then we could merge it.

2016-11-03 14:28 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +        /* @var Entity $entity */
The code uses methods from EntityTrait. So Entity is the correct hint. I general find the EntityInterface kind of useless. It's to simple.

2016-11-03 14:33 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +     * - fieldList: (deprecated) use fields instead.
fixed

2016-11-03 14:33 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +     * - fieldList: (deprecated) use fields instead
fixed

2016-11-03 14:33 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +     * - fieldList: (deprecated) use fields instead
fixed

2016-11-03 14:33 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +     * - fields: A whitelist of fields to be assigned to the entity. If not present
fixed

2016-11-03 14:33 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +     * - fieldList: (deprecated) use fields instead
fixed

2016-11-03 14:33 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +     * - fields: A whitelist of fields to be assigned to the entity. If not present,
fixed

2016-11-03 14:34 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +            $options['fields'] = $options['fieldList'];
fixed

2016-11-03 14:38 UTC, thinkingmedia commented on src/ORM/Marshaller.php
> +        if (isset($options['fields'])) {
fixed

2016-11-03 14:41 UTC, thinkingmedia commented
This should be done now.

2016-11-07 08:31 UTC, lorenzo commented on src/ORM/Marshaller.php
> +                    $entity->set($field, $properties[$field]);
What issue is that?

2016-11-09 22:39 UTC, thinkingmedia commented
@markstory would you like anything changed here?

2016-11-13 02:31 UTC, merged