2.x Add Stacking Flash Messages
cakephp/cakephp pull request #9664
Opened 2016-10-27 23:47 UTC by xhs345

In issue #7830 it was requested to backport the feature.

2016-10-28 03:53 UTC, markstory commented
Looks good, I think changing the internal flash message format could be surprising in a bugfix release. This might have to wait until 2.10.0

2016-10-28 04:08 UTC, xhs345 commented
It's the nice kind of surprise, but I agree :)

2016-10-28 04:31 UTC, markstory commented
I've retargeted this pull request to 2.next, but you may have to rebase to clean up the history.

2016-10-28 16:12 UTC, xhs345 commented
Branch has been rebased

2016-10-31 02:16 UTC, markstory requested changes

2016-10-31 02:16 UTC, markstory commented on lib/Cake/Controller/Component/FlashComponent.php
> +		$newMessage = array(
In 3.x we support a `clear` option to allow for the flash message stack to be reset/cleared when adding a new message. Could we also have that option in 2.x? Without it maintaining existing behavior is not possible for those who want/need it.

2016-10-31 02:18 UTC, markstory commented on lib/Cake/Controller/Component/FlashComponent.php
> +		$newMessage = array(
We also have `clear` as a class level configuration option which makes it easy to preserve existing behavior through a configuration change.

2016-10-31 03:40 UTC, xhs345 commented
Yea, sounds like a good idea and was easy to add

2016-11-01 13:09 UTC, ravage84 approved these changes
Looks good, just some nitpicking...

2016-11-01 13:09 UTC, ravage84 commented on lib/Cake/Controller/Component/FlashComponent.php
> +		'clear' => false
Haven't we agreed on a traling slash? :confused: 
Anyway, I would do so.

2016-11-01 13:09 UTC, ravage84 commented on lib/Cake/View/Helper/FlashHelper.php
> +			$out .= $this->_View->element($message['element'], $message);
Nitpicking: Could we add a new line after/before each new element? Would produce nice HTML.

2016-11-01 15:58 UTC, xhs345 commented on lib/Cake/View/Helper/FlashHelper.php
> +			$out .= $this->_View->element($message['element'], $message);
Right now the formatting is done in the view element and the HTML is looking quite nice by default imo 
![screenshot 2016-11-01 08 57 40](https://cloud.githubusercontent.com/assets/9390869/19896376/59461a20-a011-11e6-96a5-3da2d73d4461.png)

2016-11-01 17:01 UTC, ravage84 commented on lib/Cake/Controller/Component/FlashComponent.php
> +		'clear' => false
Doh! Trailing comma, sorry :smirk_cat:

2016-11-01 19:51 UTC, xhs345 commented on lib/Cake/Controller/Component/FlashComponent.php
> +		'clear' => false
I don't know what you agreed on, but it looks like a trailing comma is not being used in similar instances the other components currently

2016-11-01 19:52 UTC, xhs345 commented on lib/Cake/View/Helper/FlashHelper.php
> +			$out .= $this->_View->element($message['element'], $message);
Ok, guess I don't know which element and HTML you're referring to

2016-11-02 01:24 UTC, merged