Supprt Unicode escape sequence in Postgresql
cakephp/cakephp pull request #9708
Opened 2016-11-04 17:54 UTC by atkrad

I,ve fixed my problem on save Unicode JSON in Postgresql with this pull request.

**Error Message:**
```
SQLSTATE[22P05]: Untranslatable character: 7 
ERROR:  unsupported Unicode escape sequence
DETAIL:  Unicode escape values cannot be used for code point values above 007F when the server encoding is not UTF8.
CONTEXT:  JSON data, line 1: {\"first_name\":...
```

2016-11-04 18:40 UTC, dereuromark commented on src/Database/Type/JsonType.php
> +        if ($driver instanceof Postgres) {
Are any other json Flags revelant as well?

2016-11-04 18:44 UTC, ADmad commented
This part of error message is interesting "...when the server encoding is not UTF8". Does this mean the problem wouldn't occur if using utf8 encoding?

2016-11-04 18:52 UTC, atkrad commented
I've tested with "jsonb".

On Nov 4, 2016 22:11, "Mark Sch." <notifications@github.com> wrote:

> *@dereuromark* commented on this pull request.
> ------------------------------
>
> In src/Database/Type/JsonType.php
> <https://github.com/cakephp/cakephp/pull/9708#pullrequestreview-7261716>:
>
> > @@ -42,7 +43,12 @@ public function toDatabase($value, Driver $driver)
>              throw new InvalidArgumentException('Cannot convert a resource value to JSON');
>          }
>
> -        return json_encode($value);
> +        $options = 0;
> +        if ($driver instanceof Postgres) {
>
> Are any other json Flags revelant as well?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/cakephp/cakephp/pull/9708#pullrequestreview-7261716>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAVchG_sh8ylnqqcHNMhRAUlgS6HbRcJks5q63xPgaJpZM4Kp0kB>
> .
>

2016-11-04 19:04 UTC, atkrad commented on src/Database/Type/JsonType.php
> +        if ($driver instanceof Postgres) {
@dereuromark I don't know. I've tested on Postgresql with "jsonb" as data type.

2016-11-04 19:04 UTC, atkrad commented on src/Database/Type/JsonType.php
> +        if ($driver instanceof Postgres) {
@dereuromark I don't know. I've tested on Postgresql with "jsonb" as data type.

2016-11-04 19:19 UTC, thinkingmedia commented
**Postgresql** does not support **none** UTF8 for storing JSON.

## Postgresql IRC history

> if you want to use json/jsonb, you are going to be best served by using a UTF8-encoded database, or not using non-ascii unicode escapes in json at all.

What I've found googling this topic. Is that Postgresql does not want to handle migrating JSON data between encoding standards every time a user upgrades their database. If you change encoding Postgresql will *not* rewrite all JSON to the new encoding, and it will not convert it when reading it.

It will just store it as low-ASCII if it is not UTF8. Therefore, anything above **007F** is out of range no matter when encoder you are using.

Disabling JSON encoding in PHP will just result in unexpected problems.

2016-11-12 16:20 UTC, markstory commented
Any way we could get an test case where unicode data is being inserted into a JSON column? That would help ensure we don't have issues with other databases, and ensure there is aren't regressions in the future.

2016-11-15 08:38 UTC, lorenzo commented
@atkrad do you mind trying to always apply that flag, without checking for postgres? I would like to see if it is a problem for other databases

2016-11-15 09:42 UTC, atkrad commented
@lorenzo Do you want from me to rewrite code without checking for postgres?

2017-02-26 04:13 UTC, markstory requested changes
This will need some sort of test coverage before it can be merged.

2017-10-08 01:40 UTC, markstory commented
I finally got around to looking at this again, and the `JSON_UNESCAPED_UNICODE` cannot be applied in all cases. From my testing it resulted in broken inserts in MySQL for high-code points. I'm also not sure we want to be working around limitations in Postgres. The [postgres docs](https://www.postgresql.org/docs/9.4/static/datatype-json.html) states

>  However, the input function for jsonb is stricter: it disallows Unicode escapes for non-ASCII characters (those above U+007F) unless the database encoding is UTF8. 

It sounds like you need to either use the `json` type or correct the encoding of your database.

2017-10-08 01:40 UTC, closed without merging