BreadcrumbsHelper::render() returns null with no crumbs
cakephp/cakephp pull request #9801
Opened 2016-11-26 09:56 UTC by mirko-pagliai

See https://github.com/cakephp/cakephp/issues/9798

The `render()` method should return `null` (or a blank string) if empty (now it returns the string `<ul></ul>`), in other words if you have not added any crumb.

2016-11-26 10:11 UTC, dereuromark commented on src/View/Helper/BreadcrumbsHelper.php
> +        if (empty($this->crumbs)) {
No cloaking please if possible. if (!...)

2016-11-26 10:12 UTC, dereuromark commented
Empty String makes more sense imo. Keeps Return types at a Minimum.

2016-11-26 10:13 UTC, mirko-pagliai commented on src/View/Helper/BreadcrumbsHelper.php
> +        if (empty($this->crumbs)) {
Sorry, what's "cloaking"?

2016-11-26 15:13 UTC, markstory commented on src/View/Helper/BreadcrumbsHelper.php
> +        if (empty($this->crumbs)) {
`empty()` eats a bunch of values where as `!== null` or `count($this->crumbs) === 0` are more specific.

2016-11-26 15:14 UTC, markstory requested changes

2016-11-26 15:14 UTC, markstory commented on src/View/Helper/BreadcrumbsHelper.php
> +     * @return string|null The breadcrumbs trail
Instead of adding more types could we just return ''?

2016-11-26 15:14 UTC, markstory commented on tests/TestCase/View/Helper/BreadcrumbsHelperTest.php
> +        $this->assertEmpty($this->breadcrumbs->render());
You might want `assertSame('', $this->breadcrumbs->render())` or `assertNull()`.

2016-11-26 15:30 UTC, dereuromark commented on src/View/Helper/BreadcrumbsHelper.php
> +        if (empty($this->crumbs)) {
See http://book.cakephp.org/3.0/en/contributing/cakephp-coding-conventions.html#careful-when-using-empty-isset
So `if (!$this->crumbs)` would always be better as it doesnt hide spelling mistakes etc.

2016-11-26 15:31 UTC, dereuromark commented on tests/TestCase/View/Helper/BreadcrumbsHelperTest.php
> +        $this->assertEmpty($this->breadcrumbs->render());
When the result is always string I would also go for the first.

2016-11-27 09:56 UTC, mirko-pagliai commented
Now it should be ok :)

2016-11-27 10:02 UTC, merged

2016-11-27 10:02 UTC, dereuromark commented
Perfect, Thanks!

2017-03-09 17:07 UTC, atalayk commented
Breadcrumbs are only visible in the current view. As soon as go into another view, crumbs disappear.

2017-03-09 18:27 UTC, mirko-pagliai commented
@atalayk ???
This is a PR.