Move default into class so simpler ::class syntax can be used.
cakephp/cakephp pull request #9806
Opened 2016-11-27 11:44 UTC by dereuromark

The default should be moved inside the class to allow simpler Application setup:
```php
		$middleware
			->add(MaintenanceMiddleware::class)
			->add(ErrorHandlerMiddleware::class)
			->add(AssetMiddleware::class)
			->add(RoutingMiddleware::class);
```
etc

No need to force instantiation here.

2016-11-27 14:27 UTC, dereuromark commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +            $renderer = Configure::read('Error.exceptionRenderer');
That makes indeed more sense alltogether. Wanna help me adjust the PR here?

2016-11-27 14:50 UTC, dereuromark commented
Looks good to me.

2016-11-27 22:23 UTC, markstory commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +        }
Any reason this couldn't be done in the constructor? Are you trying to avoid the class load?

2016-11-28 00:49 UTC, ADmad commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +        }
I don't see the need to check for default / fallback class so early until it needs to be actually instantiated.

2016-11-28 02:20 UTC, markstory commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +        }
Ok.

2016-11-28 20:40 UTC, thinkingmedia commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +        }
Isn't this a case for using `$_defaultConfig`?

2016-11-28 21:51 UTC, markstory commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +        }
Good point, but that would introduce strings again, which is what I think @dereuromark is trying to remove as well.

2016-11-28 22:57 UTC, dereuromark commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +        }
No, I only wanted to not have it outside to be a requirement to be passed in :) See the linked app PR

2016-11-29 02:37 UTC, markstory commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +            $this->renderer = $this->config('exceptionRender') ?: ExceptionRenderer::class;
Shouldn't this be `exceptionRenderer`?

2016-11-29 11:22 UTC, ADmad commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +            $this->renderer = $this->config('exceptionRender') ?: ExceptionRenderer::class;
Yup, typo, I'll fix it.

2016-12-07 15:36 UTC, dereuromark commented
I rebased and fixed the name.

2016-12-07 22:02 UTC, markstory requested changes

2016-12-07 22:02 UTC, markstory commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +            $this->exceptionRenderer = $this->config('exceptionRender') ?: ExceptionRenderer::class;
Still needs to be `exceptionRenderer`.

2016-12-07 22:15 UTC, dereuromark commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +            $this->exceptionRenderer = $this->config('exceptionRender') ?: ExceptionRenderer::class;
Oh that name.

2016-12-08 01:53 UTC, markstory commented on src/Error/Middleware/ErrorHandlerMiddleware.php
> +            $this->exceptionRenderer = $this->config('exceptionRender') ?: ExceptionRenderer::class;
Yeah the config value doesn't!atch the one in the app skeleton

2016-12-09 02:30 UTC, merged