fixes #9915
cakephp/cakephp pull request #9923
Opened 2016-12-27 09:16 UTC by mlingureanu

will solve issue https://github.com/cakephp/cakephp/issues/9915 
paginate or find using virtual fields and param fields, return wrong results on virtual fields

documentation should be updated:
http://book.cakephp.org/2.0/en/models/virtual-fields.html#limitations-of-virtualfields

2016-12-27 10:20 UTC, dereuromark requested changes

2016-12-27 10:20 UTC, dereuromark commented on lib/Cake/Model/Datasource/DboSource.php
> +						if (count($fieldExploded) == 2 && str_replace('`', '', $fieldExploded[0]) == $LinkModel->alias) {
Please use ===

2016-12-27 14:46 UTC, mlingureanu commented on lib/Cake/Model/Datasource/DboSource.php
> +						if (count($fieldExploded) == 2 && str_replace('`', '', $fieldExploded[0]) == $LinkModel->alias) {
done

2016-12-27 20:12 UTC, markstory reviewed
There are a bunch of tests that look like they need to be updated. I can take a look later this week if you're not familiar with fixing tests.

2016-12-27 20:12 UTC, markstory commented on lib/Cake/Model/Datasource/DboSource.php
> +						if (count($fieldExploded) === 2 && str_replace('`', '', $fieldExploded[0]) === $LinkModel->alias) {
The backticks here should be `$this->startQuote` and `$this->endQuote`. Unfortunately the quotes are not the same across all the supported databases. For example SQLServer uses `[` and `]`.

2016-12-27 20:12 UTC, markstory commented on lib/Cake/Model/Datasource/DboSource.php
> +						if (count($fieldExploded) === 2 && str_replace('`', '', $fieldExploded[0]) === $LinkModel->alias) {
You might want to consider using a regexp, as it might be a simpler way to extract the alias/field out of the column name.

2016-12-28 18:54 UTC, dereuromark approved these changes

2016-12-28 18:54 UTC, dereuromark commented
Tests are still red, though.

2016-12-29 00:53 UTC, chinpei215 commented
Related to #4589

2017-04-29 18:33 UTC, dereuromark commented
@mlingureanu Are you still interested in getting this fixed up?
It currently looks like it becomes stale and it is not mergeable in the current state.

2017-04-29 19:38 UTC, mlingureanu commented
I don't have time to update unit tests.

2018-02-19 20:53 UTC, dereuromark commented
Since there seems no interest in getting this done, and 2.x is now in maintenance only mode, closing for now. Please open a new and complete PR if still interested.

2018-02-19 20:53 UTC, closed without merging