Improving PHPStan configuration
cakephp/cakephp pull request #9945
Opened 2016-12-30 20:46 UTC by ondrejmirtes

2016-12-30 20:54 UTC, dereuromark commented on src/Shell/I18nShell.php
> +    private $_paths;
protected

2016-12-30 20:55 UTC, dereuromark commented on src/TestSuite/LegacyRequestDispatcher.php
> +	private $_test;
also protected

2016-12-30 20:58 UTC, ADmad requested changes

2016-12-30 20:58 UTC, ADmad commented on src/Shell/PluginShell.php
> + * @property mixed $Assets
`@property \Cake\Shell\Task\AssetsTask $Assets`

Similarly the other 2 properties belows are also tasks from `\Cake\Shell\Task\` namespace.

2016-12-30 21:02 UTC, ondrejmirtes commented
Please don't merge it right away :) I'd like to bring the number of errors to as low as possible.

2016-12-30 21:06 UTC, ADmad commented
@ondrejmirtes I have a couple handy for you :) https://gist.github.com/ADmad/ca6627799292d155d36e6555e7b4a8f4

2016-12-30 21:11 UTC, ondrejmirtes commented
I think you can  commit and push to my branch:

```
git push git@github.com:ondrejmirtes/cakephp.git HEAD:phpstan
```

2016-12-30 21:15 UTC, ADmad commented
I believe that would require you to give me commit rights to your fork. It's no biggie, I cam make those changes later on our repo.

2016-12-31 00:05 UTC, ondrejmirtes commented
I pushed a custom class reflection extension to cover the Association/Table mixin behaviour, to prevent these errors:

```
------ ------------------------------------------------------------------- 
  Line   src/ORM/Association/HasOne.php                                     
 ------ ------------------------------------------------------------------- 
  153    Call to an undefined method Cake\ORM\Association\HasOne::alias().  
 ------ ------------------------------------------------------------------- 
 ------ ---------------------------------------------------------------------- 
  Line   src/ORM/Association/BelongsTo.php                                     
 ------ ---------------------------------------------------------------------- 
  208    Call to an undefined method Cake\ORM\Association\BelongsTo::alias().  
 ------ ---------------------------------------------------------------------- 
 ------ ------------------------------------------------------------------------ 
  Line   src/ORM/Association/Loader/SelectWithPivotLoader.php                    
 ------ ------------------------------------------------------------------------ 
  174    Access to an undefined property                                         
         Cake\ORM\Association\Loader\SelectWithPivotLoader::$_junctionProperty.  
 ------ ------------------------------------------------------------------------ 
 ------ ---------------------------------------------- 
  Line   src/ORM/Association/BelongsToMany.php         
 ------ ---------------------------------------------- 
  550    Call to an undefined method                   
         Cake\ORM\Association\BelongsToMany::alias().  
  1027   Call to an undefined method                   
         Cake\ORM\Association\BelongsToMany::alias().  
 ------ ---------------------------------------------- 
 ------ -------------------------------------------------------------------- 
  Line   src/ORM/Association/HasMany.php                                     
 ------ -------------------------------------------------------------------- 
  658    Call to an undefined method Cake\ORM\Association\HasMany::alias().  
 ------ -------------------------------------------------------------------- 
```

PHPStan now knows that methods in Association children can come from the Table class and checks correctly their usage. Do you like it?

2016-12-31 00:29 UTC, dereuromark commented on config/PHPStan/AssociationTableMixinClassReflectionExtension.php
> +    private function _getTableReflection(): ClassReflection
We dont need the underscores here as prefix.

2016-12-31 00:30 UTC, dereuromark commented on src/TestSuite/LegacyRequestDispatcher.php
> +    /** @var \Cake\TestSuite\IntegrationTestCase */
unfolded maybe?

2016-12-31 01:10 UTC, ondrejmirtes commented on config/PHPStan/AssociationTableMixinClassReflectionExtension.php
> +    private function _getTableReflection(): ClassReflection
stickler-ci complained about it

2016-12-31 01:10 UTC, ondrejmirtes commented on src/TestSuite/LegacyRequestDispatcher.php
> +    /** @var \Cake\TestSuite\IntegrationTestCase */
I don't understand?

2016-12-31 01:19 UTC, dereuromark commented on src/TestSuite/LegacyRequestDispatcher.php
> +    /** @var \Cake\TestSuite\IntegrationTestCase */
Usually we use multi line for those. This is a single line annotation,

2016-12-31 01:19 UTC, dereuromark commented on config/PHPStan/AssociationTableMixinClassReflectionExtension.php
> +    private function _getTableReflection(): ClassReflection
Ah ok, but _ should be protected then.

2016-12-31 14:03 UTC, ADmad commented
You'll need to update this test case https://travis-ci.org/cakephp/cakephp/jobs/187818797#L698

2016-12-31 14:53 UTC, ondrejmirtes commented
@ADmad I meant to ask whether you think the `config/PHPStan` is the right directory for this kind of stuff? I'd much rather add a new directory `build` that sets a more clear purpose.

2016-12-31 15:05 UTC, dereuromark commented
I think it is fine as it is.

2016-12-31 16:16 UTC, ADmad commented
I think having the phpstan files inside `tests/` would be better.

2016-12-31 16:18 UTC, ADmad commented
> Do you consider removing the build from allow_failures when we get the number of errors to zero?

Yes I would.

2017-01-01 08:28 UTC, ADmad requested changes

2017-01-01 08:28 UTC, ADmad commented on tests/TestCase/Filesystem/FolderTest.php
> +                CORE_PATH . 'config/PHPStan',
Please use `DS` instead of `/` else the test will fail on windows.

2017-01-01 08:28 UTC, ADmad commented on tests/TestCase/Filesystem/FolderTest.php
> +                CORE_PATH . 'config/PHPStan/AssociationTableMixinClassReflectionExtension.php',
Same as above, use `DS` instead of `/` else the test will fail on windows.

2017-01-01 08:50 UTC, ADmad commented
@ondrejmirtes This seems good to merge once the phpstan files are moved from `/config` to `/tests`.

You can open new PR with further fixes. Incremental changes will be easier to review.

2017-01-02 23:23 UTC, ondrejmirtes commented
I pushed a new version, let's see if it builds :)

2017-01-03 03:52 UTC, ADmad commented
Getting there: "Found 27 errors".

I am merging this to avoid more merge conflicts.

2017-01-03 03:52 UTC, merged