CounterCache should ignore dirty fields
cakephp/cakephp pull request #9960
Opened 2017-01-03 00:52 UTC by cleptric

This implements #9380

2017-01-03 00:58 UTC, dereuromark commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                    isset($config['ignore_if_dirty']) &&
Mind you casing. Check out what markstory's proposal actually was: ignoreIfDirty.

2017-01-03 01:15 UTC, dereuromark commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                $entityAlias = strtolower(Inflector::singularize($regitsryAlias));
type regitsry?

2017-01-03 01:16 UTC, dereuromark commented on tests/TestCase/ORM/Behavior/CounterCacheBehaviorTest.php
> +        $this->assertEquals(1, $user->get('posts_published'));
We should use assertSame always if possible to avoid type mismatches.

2017-01-03 03:16 UTC, ADmad commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                    isset($config['ignoreIfDirty']) &&
This condition is repeated.

2017-01-03 09:21 UTC, dereuromark commented
The idea on the issue ticket was to have the name `ignoreDirty` (shorter), what do people think? I like it.

2017-01-03 11:18 UTC, cleptric commented on CounterCacheRework.php
> +    protected function _processAssociations(Event $event, EntityInterface $entity, $executeQueries = true)
Did I missed sth.?

2017-01-03 12:27 UTC, cleptric commented
Why is stickler-ci complaining now?

2017-01-03 12:33 UTC, ADmad commented
The phpcs job on travis passed so ignore stickler-ci :stuck_out_tongue:

2017-01-03 12:35 UTC, ADmad commented
I don't think you meant to include `CounterCacheRework.php` in the PR.

2017-01-03 12:40 UTC, cleptric commented
True story, thanks for the hint 👍

2017-01-03 12:50 UTC, dereuromark commented
Maybe squash?

2017-01-03 12:55 UTC, cleptric commented
@dereuromark or did you meant the whole PR?

2017-01-03 13:10 UTC, cleptric commented
Ok, I squashed everything into one commit and renamed the option to `ignoreDirty `.
Anything else?

2017-01-03 14:18 UTC, dereuromark commented
:100:  :+1:

2017-01-03 14:22 UTC, ADmad commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                if (is_int($field)) {
Why not just continue the loop for this case?  If `$field` is integer means no special options have being set for this field and hence no `ignoreDirty` either.

2017-01-03 14:25 UTC, ADmad requested changes

2017-01-03 14:25 UTC, ADmad commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                $entityAlias = strtolower(Inflector::singularize($registryAlias));
This will fail is a non default association property name is used. Use `$assocation->property()` instead.

2017-01-03 14:25 UTC, ADmad commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                    $this->_ignoreDirty = Hash::merge($this->_ignoreDirty, [
`Hash::merge()` seems unnecessary here. Can just do `$this->_ignoreDirty[$foo] = $bar`.

2017-01-04 16:55 UTC, cleptric commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                    $this->_ignoreDirty = Hash::merge($this->_ignoreDirty, [
But then I can't ignore more then one field per Model?

2017-01-04 21:38 UTC, ADmad commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                    $this->_ignoreDirty = Hash::merge($this->_ignoreDirty, [
Not if you do `$this->_ignoreDirty[$registryAlias] = [..]`.  Though I am not totally sure if `$registryAlias` can be repeated, so never mind, it's fine this way.

2017-01-04 22:13 UTC, markstory commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                    $this->_ignoreDirty = Hash::merge($this->_ignoreDirty, [
Wouldn't

```php
$this->_ignoreDirty[$registryAlias][$field] = true;
```

Do the same thing as what we have right now?

2017-01-05 11:12 UTC, cleptric commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                    $this->_ignoreDirty = Hash::merge($this->_ignoreDirty, [
It does 👍. I added some tests to check this, too.

2017-01-05 11:14 UTC, cleptric commented on src/ORM/Behavior/CounterCacheBehavior.php
> +                $entityAlias = strtolower(Inflector::singularize($registryAlias));
Done

2017-01-05 14:46 UTC, markstory commented on src/ORM/Behavior/CounterCacheBehavior.php
> +            }
Should `_ignoreDirty` be reset at the end of the afterSave method?

2017-01-05 14:54 UTC, ADmad approved these changes

2017-01-05 16:08 UTC, cleptric commented on src/ORM/Behavior/CounterCacheBehavior.php
> +            }
It wouldn't hurt I guess :)

2017-01-05 16:14 UTC, cleptric commented
I committed all the requested changes

2017-01-11 02:10 UTC, merged